#ifndef __INCLUDE_CONSTANTS_ENTITY_PROJECTILE_H__
#define __INCLUDE_CONSTANTS_ENTITY_PROJECTILE_H__

// Projectile.id
#define PROJECTILE_LEMON 0
#define PROJECTILE_SHOTCOUNTER_BULLET 1
// ...
#define PROJECTILE_OMEGA_ZERO 38
// ...
#define PROJECTILE_ENTITY_COUNT 48

#endif  // __INCLUDE_CONSTANTS_ENTITY_PROJECTILE_H__
