#!/usr/bin/env -S deno run --allow-read

import { Command } from '@cliffy/command';
import { basename, dirname, extname, join } from '@std/path';
import { existsSync } from '@std/fs';
import { GraphicHeader, SEPARATOR } from '../common/index.ts';

/**
 * header.json から アセンブリファイル を生成するスクリプト (e.g. sprites/dynamic/anubis/sheet/header.json)
 * 実行すると次のようなファイルが生成されます (正確には標準出力に出力されるのでリダイレクトしてください)
 * グラフィックデータ(.incbinしてるやつら)のサイズからオフセットを計算する必要があるので、 このスクリプトの実行前に、グラフィックデータをビルドする必要があります。
 *
 * .section .rodata
 * .balign 4, 0
 * .global gGraphicHeader_XXX
 * gGraphicHeader_XXX:
 * @ ヘッダ列 (include/gfx.h の Graphic[])
 *   @ include/gfx.h の Graphic
 *     .4byte offset
 *     .4byte xxxxxxxx
 *     .2byte xxxx, xxxx
 *     @ パレットがあるなら
 *       .4byte xxxxxxxx
 *       .2byte xxxx
 *       .byte xx, xx
 *   @ header.json の data の要素数だけ繰り返し
 *     ...
 * @ グラフィックデータ
 *   .incbin "aaa/bbb.4bpp" (もしくは .lz)
 *   .incbin "aaa/bbb.gbapal" (もしあれば)
 *   ...
 */

type JsonData = {
  label?: string;
  data: GraphicHeader[];
};

type GraphicInfo = {
  name: string;
  size: number;
  color: number;
  files: string[];
  hdrOnly: boolean;
};

// e.g.
// ./tools/dev/graphic_header.ts sprites/dynamic/zero/idle/sheet/header.json > tmp/header.inc
const main = async () => {
  const toolname = basename(import.meta.filename || '');
  if (!toolname) {
    console.error('Error: Could not determine tool name from import.meta.filename');
    Deno.exit(1);
  }

  const { args, options } = await new Command()
    .name('graphic_header.ts')
    .version('1.0.0')
    .description('Create a asm header file from a graphic json folder.')
    .argument('<json:string>', 'header.json のファイルパス')
    .option('--verbose', 'verbose')
    .option('-l, --label=[val:string]', 'Force label', { default: '' })
    .usage('sprites/dynamic/zero/idle/sheet/header.json')
    .parse(Deno.args);

  const source = args[0];
  const base = dirname(source); // e.g. sprites/dynamic/zero/idle/sheet/

  const json = JSON.parse(Deno.readTextFileSync(args[0])) as JsonData;
  const graphics = json.data;
  if (options.verbose) {
    console.error(source); // stderr
    console.error(json); // stderr
  }

  const infos: GraphicInfo[] = [];
  let headerSize = 12;

  for (let i = 0; i < graphics.length; i++) {
    const g = graphics[i];

    let name: string;
    const ext = extname(g.name);
    switch (ext) {
      case '.4bpp': {
        name = g.name;
        break;
      }
      case '.lz': {
        name = g.name;
        break;
      }
      case '.png': {
        if (g.name.endsWith('.lz.png')) {
          name = g.name.replaceAll('.lz.png', '.lz');
        } else {
          name = g.name.replaceAll('.png', '.4bpp');
        }
        break;
      }
      default: {
        name = g.name;
        break;
      }
    }

    const path = join(base, name);
    if (!existsSync(path)) {
      throw new Error('File not found: ' + path);
    }

    const size = Deno.statSync(path).size;

    let color = 0;
    if (g.palette != null) {
      headerSize = 20;
      color = g.palette.color;
    }

    let files: string[] = [];
    if (g.files != null && g.files.length > 0) {
      files = g.files.map((f) => join(base, f));
    } else {
      files.push(path);
      if (g.palette != null) {
        if (g.palette.color > 0) {
          let palettePath = name.replaceAll('.4bpp.lz', '.gbapal');
          palettePath = palettePath.replaceAll('.4bpp', '.gbapal');
          palettePath = palettePath.replaceAll('.lz', '.lz.gbapal');
          files.push(join(base, palettePath));
        }
      }
    }

    const hdrOnly = g.hdrOnly ?? false;
    infos.push({
      name,
      size: hdrOnly ? 0 : size,
      color,
      files,
      hdrOnly,
    });
  }

  const headers: string[] = [];
  for (let i = 0; i < graphics.length; i++) {
    const g = graphics[i];
    const info = infos[i];
    let src = headerSize * (graphics.length - i);
    if (i > 0) {
      src += sum(infos.slice(0, i).map((i) => i.size));
      src += sum(infos.slice(0, i).map((i) => i.color * 2));
    }
    let header = `\t@ Graphic ${i}
\t.4byte ${src} @ src offset, address = . + src
\t.4byte ${(BigInt(g.ofs) << 22n) | BigInt(info.size)} \t@ bits 0..21: bytesize, 22..: dst offset in VRAM
\t.2byte ${g.chunkSize} \t@ chunk size
\t.2byte ${getProps(g)} \t@ props: ${g.props.join(', ')}`;

    if (g.palette != null) {
      src += info.size - 12;
      header += `
\t\t@ Palette
\t\t.4byte ${src}
\t\t.2byte ${info.color * 2} @ bytesize
\t\t.byte 0, ${g.palette.id} @ lz77, palette_ID`;
    }

    headers.push(header);
  }

  let result = `@ Generated by the tools/dev/${toolname}. DO NOT EDIT!\n@ source: ${source}\n\n`;

  /**
   * .section .rodata
   * .balign 4, 0
   * .global [label]
   * [label]:
   */
  const label = options.label || json.label;
  result += `.section .rodata\n.balign 4, 0\n\n.global ${label}\n${label}:\n`;

  result += headers.join('\n') + `\n\n\t${SEPARATOR}\n\n@ GraphicData:\n`;

  infos.forEach((info) => {
    if (!info.hdrOnly) {
      info.files.forEach((file) => {
        result += `\t.incbin "${file}"\n`;
      });
    }
  });

  console.log(result);
};

const getProps = (g: GraphicHeader): number => {
  let props = 0;
  if (g.props.includes('4bpp')) {
    props |= 0x20;
  }
  if (g.props.includes('8bpp')) {
    props |= 0x40;
  }
  if (g.props.includes('lz77')) {
    props |= 0x02;
  }
  if (g.props.includes('no_pal')) {
    props |= 0x04;
  }
  if (g.props.includes('chunked')) {
    props |= 0x01;
  }
  return props;
};

const sum = (numbers: number[]) => {
  return numbers.reduce((accumulator, current) => accumulator + current, 0);
};

main();
