Text_NurseV1_00:: @ 0x083734C9
Str_0A29:
.if ENGLISH
	.string "I double\n"
	.string "your\n"
	.string "vitality.$"
.else
	.string "わたくしの力で\n"
	.string "あなたのライフを2倍に\n"
	.string "してさしあげましょう$"
.endif

Text_NurseV1_01:: @ 0x083734EA
Str_0A4A:
.if ENGLISH
	.string "I increase\n"
	.string "vitality\n"
	.string "slightly.$"
.else
	.string "わたしの力で\n"
	.string "あなたのライフゲージを\n"
	.string "少しだけふやしてあげる$"
.endif

Text_NurseV1_02:: @ 0x0837350B
Str_0A6B:
.if ENGLISH
	.string "I can raise\n"
	.string "vitality\n"
	.string "a tiny bit.$"
.else
	.string "ほんの少しだけど\n"
	.string "あなたのライフゲージを\n"
	.string "ふやしてあげられるの$"
.endif

Text_NurseV1_03:: @ 0x0837352C
Str_0A8C:
.if ENGLISH
	.string "Use my power\n"
	.string "to boost\n"
	.string "vitality!$"
.else
	.string "少しだけライフゲージを\n"
	.string "ふやしたいのなら\n"
	.string "わたしの力をつかってね！$"
.endif

Text_NurseV1_04:: @ 0x08373550
Str_0AB0:
.if ENGLISH
	.string "Let me boost\n"
	.string "your\n"
	.string "vitality!$"
.else
	.string "ライフゲージを少し\n"
	.string "ふやしたいときは\n"
	.string "わたしにまかせて！$"
.endif

Text_NurseV1_05:: @ 0x0837356E
Str_0ACE:
.if ENGLISH
	.string "I become\n"
	.string "a Sub Tank\n"
	.string "to help you.$"
.else
	.string "サブタンクにかわって\n"
	.string "あなたのことを\n"
	.string "助けてあげるわ$"
.endif

Text_NurseV1_06:: @ 0x0837358A
Str_0AEA:
.if ENGLISH
	.string "If you need\n"
	.string "a Sub Tank,\n"
	.string "I can help!$"
.else
	.string "もしサブタンクが\n"
	.string "ひつようなときは\n"
	.string "わたしの力をかすわ！$"
.endif

Text_NurseV1_07:: @ 0x083735A8
Str_0B08:
.if ENGLISH
	.string "Use my power\n"
	.string "to increase\n"
	.string "lives by 3!$"
.else
	.string "わたしの力で\n"
	.string "のこりにんずうを\n"
	.string "3人ふやしてあげるわ！$"
.endif

Text_NurseV1_08:: @ 0x083735C6
Str_0B26:
.if ENGLISH
	.string "If you want\n"
	.string "3 more lives\n"
	.string "call on me!$"
.else
	.string "のこりにんずうを\n"
	.string "3人ふやしたいときは\n"
	.string "わたしが力をかすわよ！$"
.endif

Text_NurseV1_09:: @ 0x083735E8
Str_0B48:
.if ENGLISH
	.string "My energy\n"
	.string "can heal\n"
	.string "8 vitality.$"
.else
	.string "わたしはあなたの体力を\n"
	.string "8メモリかいふくさせる\n"
	.string "力があるのよ$"
.endif

Text_NurseV1_10:: @ 0x0837360A
Str_0B6A:
.if ENGLISH
	.string "I heal 8\n"
	.string "vitality\n"
	.string "for you.$"
.else
	.string "わたしの力で\n"
	.string "あなたの体力を8メモリ\n"
	.string "かいふくしてあげましょう$"
.endif

Text_NurseV1_11:: @ 0x0837362D
Str_0B8D:
.if ENGLISH
	.string "Let me heal\n"
	.string "8 vitality\n"
	.string "for you.$"
.else
	.string "8メモリだけ\n"
	.string "あなたの体力を\n"
	.string "かいふくしてあげるよ$"
.endif

Text_NurseV1_12:: @ 0x08373649
Str_0BA9:
.if ENGLISH
	.string "Wounded?\n"
	.string "I can heal\n"
	.string "8 vitality.$"
.else
	.string "体力がへったときは\n"
	.string "わたしが8メモリ\n"
	.string "かいふくしてあげるね$"
.endif

Text_NurseV1_13:: @ 0x08373669
Str_0BC9:
.if ENGLISH
	.string "If you get\n"
	.string "hurt, I heal\n"
	.string "8 vitality.$"
.else
	.string "体力がへってきたら\n"
	.string "わたしが8メモリ\n"
	.string "かいふくしてあげるよ$"
.endif

Text_NurseV1_14:: @ 0x08373689
Str_0BE9:
.if ENGLISH
	.string "Use me when\n"
	.string "you need\n"
	.string "8 vitality!$"
.else
	.string "体力を8メモリ\n"
	.string "かいふくしたいときは\n"
	.string "わたしの力を使って！$"
.endif

Text_NurseV1_15:: @ 0x083736AB
Str_0C0B:
.if ENGLISH
	.string "My powers\n"
	.string "can heal\n"
	.string "8 vitality.$"
.else
	.string "わたしの力を使えば\n"
	.string "あなたの体力を8メモリ\n"
	.string "かいふくできるわ$"
.endif

Text_NurseV1_16:: @ 0x083736CE
Str_0C2E:
.if ENGLISH
	.string "Just for\n"
	.string "you, I heal\n"
	.string "8 vitality.$"
.else
	.string "あなたのためなら\n"
	.string "体力を8メモリ\n"
	.string "かいふくしてあげるよ…$"
.endif

Text_NurseV1_17:: @ 0x083736ED
Str_0C4D:
.if ENGLISH
	.string "I can heal\n"
	.string "all of your\n"
	.string "vitality!$"
.else
	.string "あんたの体力なんて\n"
	.string "わたしの力で\n"
	.string "いっきにマンタンさ！$"
.endif

Text_NurseV1_18:: @ 0x0837370C
Str_0C6C:
.if ENGLISH
	.string "I can heal\n"
	.string "vitality\n"
	.string "completely!$"
.else
	.string "体力をマンタンに\n"
	.string "したいのなら\n"
	.string "わたしの力を使いなよ！$"
.endif

Text_NurseV1_19:: @ 0x0837372C
Str_0C8C:
.if ENGLISH
	.string "Let me heal\n"
	.string "all of your\n"
	.string "vitality.$"
.else
	.string "あんたの体力くらい\n"
	.string "このわたしがすぐに\n"
	.string "マンタンにしてあげるよ$"
.endif

Text_NurseV1_20:: @ 0x0837374E
Str_0CAE:
.if ENGLISH
	.string "Let me help!\n"
	.string "I heal all\n"
	.string "vitality!$"
.else
	.string "もし体力を\n"
	.string "マンタンにしたけりゃ\n"
	.string "わたしにまかせなよ！$"
.endif

Text_NurseV1_21:: @ 0x0837376C
Str_0CCC:
.if ENGLISH
	.string "It's my job\n"
	.string "to heal you\n"
	.string "completely!$"
.else
	.string "あんたの体力を\n"
	.string "マンタンにすることが\n"
	.string "わたしのしごとさ！$"
.endif

Text_NurseV1_22:: @ 0x0837378B
Str_0CEB:
.if ENGLISH
	.string "My powers\n"
	.string "can heal you\n"
	.string "completely.$"
.else
	.string "わたしの力を使えば\n"
	.string "あんたの体力くらい\n"
	.string "すぐにマンタンにできるよ$"
.endif

Text_NurseV1_23:: @ 0x083737B0
Str_0D10:
.if ENGLISH
	.string "Damage down.\n"
	.string "Bullets into\n"
	.string "1 vitality.$"
.else
	.string "ダメージげんてんするけど\n"
	.string "テキのエネルギーだんを\n"
	.string "体力1メモリにかえるよ$"
.endif

Text_NurseV1_24:: @ 0x083737D7
Str_0D37:
.if ENGLISH
	.string "Damage down.\n"
	.string "Bullets into\n"
	.string "1 vitality.$"
.else
	.string "テキのエネルギーだんを\n"
	.string "体力1メモリにかえるけど\n"
	.string "ダメージげんてんはあるよ$"
.endif

Text_NurseV1_25:: @ 0x083737FF
Str_0D5F:
.if ENGLISH
	.string "I drop Life\n"
	.string "Energy (S)\n"
	.string "around you!$"
.else
	.string "あなたのまわりに\n"
	.string "ライフエネルギーの小を\n"
	.string "ばらまいてあげるよ！$"
.endif

Text_NurseV1_26:: @ 0x08373820
Str_0D80:
.if ENGLISH
	.string "I scatter\n"
	.string "Life Energy\n"
	.string "(S)!$"
.else
	.string "わたしがとびまわって\n"
	.string "ライフエネルギーの小を\n"
	.string "おとしてあげるよ！$"
.endif

Text_AnimalV1_00:: @ 0x08373842
Str_0DA2:
.if ENGLISH
	.string "I'll make\n"
	.string "deadly traps\n"
	.string "non-lethal.$"
.else
	.string "ふれるとミスになる\n"
	.string "トゲやマグマを\n"
	.string "ダメージにへんかんするよ$"
.endif

Text_AnimalV1_01:: @ 0x08373861
Str_0DC1:
.if ENGLISH
	.string "I can make\n"
	.string "you run\n"
	.string "faster!$"
.else
	.string "はしるはやさを少し\n"
	.string "はやくしたいのなら\n"
	.string "ボクにまかせてくれ！$"
.endif

Text_AnimalV1_02:: @ 0x08373881
Str_0DE1:
.if ENGLISH
	.string "I can boost\n"
	.string "your speed\n"
	.string "up ladders!$"
.else
	.string "わたしの力を使えば\n"
	.string "ハシゴをはやく\n"
	.string "のぼれるッキャ！$"
.endif

Text_AnimalV1_03:: @ 0x0837389E
Str_0DFE:
.if ENGLISH
	.string "I'll help\n"
	.string "you defy\n"
	.string "gravity!$"
.else
	.string "ボクの力で\n"
	.string "かべからずりおちる\n"
	.string "そくどをおそくするよ！$"
.endif

Text_AnimalV1_04:: @ 0x083738BB
Str_0E1B:
.if ENGLISH
	.string "You won't\n"
	.string "slide back\n"
	.string "from hits!$"
.else
	.string "オイラの力は\n"
	.string "ダメージをうけたときの\n"
	.string "あとずさりをなくすことさ$"
.endif

Text_AnimalV1_05:: @ 0x083738DC
Str_0E3C:
.if ENGLISH
	.string "I save you\n"
	.string "if you fall\n"
	.string "down a pit!$"
.else
	.string "もしもキミが\n"
	.string "あなにおちたら\n"
	.string "ボクが助けてあげるよ$"
.endif

Text_AnimalV1_06:: @ 0x083738F7
Str_0E57:
.if ENGLISH
	.string "I won't let\n"
	.string "you fall\n"
	.string "down pits!$"
.else
	.string "ボクがそばにいれば\n"
	.string "キミがあなにおちても\n"
	.string "助けてあげられるよ！$"
.endif

Text_AnimalV1_07:: @ 0x08373918
Str_0E78:
.if ENGLISH
	.string "I cling to\n"
	.string "and stop\n"
	.string "certain\n"
	.string "enemies.$"
.else
	.string "とくていのテキに\n"
	.string "くっついて\n"
	.string "動けなくするのが\n"
	.string "ボクのやくめなんだ！$"
.endif

Text_AnimalV1_08:: @ 0x0837393C
Str_0E9C:
.if ENGLISH
	.string "I grab and\n"
	.string "stop certain\n"
	.string "enemies.$"
.else
	.string "ボクがとくていのテキに\n"
	.string "ピッタリくっついて\n"
	.string "動きを止めてあげる！$"
.endif

Text_AnimalV1_09:: @ 0x0837395F
Str_0EBF:
.if ENGLISH
	.string "I'll shoot\n"
	.string "ahead\n"
	.string "to help you!$"
.else
	.string "ボクはまっすぐ\n"
	.string "タマをうって\n"
	.string "キミをえんごするよ！$"
.endif

Text_AnimalV1_10:: @ 0x08373979
Str_0ED9:
.if ENGLISH
	.string "My bullets\n"
	.string "will give\n"
	.string "cover fire!$"
.else
	.string "ボクのハッシャする\n"
	.string "タマは まっすぐ\n"
	.string "とんでいくよ！$"
.endif

Text_AnimalV1_11:: @ 0x08373994
Str_0EF4:
.if ENGLISH
	.string "My shots\n"
	.string "head toward\n"
	.string "the ground!$"
.else
	.string "ボクのハッシャする\n"
	.string "タマは じめんに向かって\n"
	.string "とんでいくよ！$"
.endif

Text_AnimalV1_12:: @ 0x083739B4
Str_0F14:
.if ENGLISH
	.string "My shots\n"
	.string "hit the\n"
	.string "ground!$"
.else
	.string "ボクは じめんに向けて\n"
	.string "タマをハッシャする\n"
	.string "エルフだよ！$"
.endif

Text_HackerV1_00:: @ 0x083739D2
Str_0F32:
.if ENGLISH
	.string "I double\n"
	.string "the items\n"
	.string "you get!$"
.else
	.string "とったアイテムのりょうを\n"
	.string "2倍にしたいときは\n"
	.string "このボクが力をかすよ！$"
.endif

Text_HackerV1_01:: @ 0x083739F7
Str_0F57:
.if ENGLISH
	.string "Enemies will\n"
	.string "drop more\n"
	.string "items!$"
.else
	.string "ザコテキをたおした時に\n"
	.string "かならず\n"
	.string "アイテムがでるのさ！$"
.endif

Text_HackerV1_02:: @ 0x08373A14
Str_0F74:
.if ENGLISH
	.string "Press Up\n"
	.string "during \n"
	.string "TRIPLE ATK.$"
.else
	.string "3だんぎりの時に上を\n"
	.string "おして セイバーをふると\n"
	.string "きりあげられるよ$"
.endif

Text_HackerV1_03:: @ 0x08373A37
Str_0F97:
.if ENGLISH
	.string "Press Down\n"
	.string "during\n"
	.string "TRIPLE ATK.$"
.else
	.string "3だんぎりの時に下を\n"
	.string "おして セイバーをふると\n"
	.string "ショウゲキハが出るよ$"
.endif

Text_HackerV1_04:: @ 0x08373A5D
Str_0FBD:
.if ENGLISH
	.string "Four shots\n"
	.string "for your\n"
	.string "Buster Shot!$"
.else
	.string "バスターショットを\n"
	.string "4れんしゃにしたけりゃ\n"
	.string "ボクにまかせて！$"
.endif

Text_HackerV1_05:: @ 0x08373A7C
Str_0FDC:
.if ENGLISH
	.string "Dash + Up/\n"
	.string "Down or jump\n"
	.string "+ Up: spin.$"
.else
	.string "ダッシュ中に下か上\n"
	.string "ジャンプ中に上で\n"
	.string "かいてんぎりができるよ$"
.endif

Text_HackerV1_06:: @ 0x08373AA0
Str_1000:
.if ENGLISH
	.string "Slash at\n"
	.string "bullets to\n"
	.string "stop them.$"
.else
	.string "セイバーをふって\n"
	.string "テキのエネルギーだんを\n"
	.string "消すことができるよ$"
.endif

Text_HackerV1_07:: @ 0x08373AC0
Str_1020:
.if ENGLISH
	.string "Block shots\n"
	.string "and you'll\n"
	.string "get EC (S).$"
.else
	.string "エネルギーだんを\n"
	.string "シールドでタイミングよく\n"
	.string "ふせぐとECの小が出るよ$"
.endif

Text_HackerV1_08:: @ 0x08373AE5
Str_1045:
.if ENGLISH
	.string "+1 to your\n"
	.string "Buster Shot.$"
.else
	.string "バスターのパワーを\n"
	.string "プラス1するよ$"
.endif

Text_HackerV1_09:: @ 0x08373AF7
Str_1057:
.if ENGLISH
	.string "+1 to your\n"
	.string "Z Saber.$"
.else
	.string "セイバーのパワーを\n"
	.string "プラス1するよ$"
.endif

Text_HackerV1_10:: @ 0x08373B09
Str_1069:
.if ENGLISH
	.string "+1 to your\n"
	.string "Rod.$"
.else
	.string "ロッドのパワーを\n"
	.string "プラス1するよ$"
.endif

Text_HackerV1_11:: @ 0x08373B1A
Str_107A:
.if ENGLISH
	.string "+1 to your\n"
	.string "Shield.$"
.else
	.string "シールドのパワーを\n"
	.string "プラス1するよ$"
.endif

Text_HackerV1_12:: @ 0x08373B2C
Str_108C:
.if ENGLISH
	.string "Speed up\n"
	.string "your weapon\n"
	.string "charge.$"
.else
	.string "ブキをチャージする\n"
	.string "時間をもう少し\n"
	.string "はやくしてあげるよ$"
.endif

Text_HackerV1_13:: @ 0x08373B4B
Str_10AB:
.if ENGLISH
	.string "Certain foes\n"
	.string "become\n"
	.string "Mettaurs.$"
.else
	.string "とくていのザコテキなんて\n"
	.string "ボクの力でメットールに\n"
	.string "かえちゃうんだから！$"
.endif

Text_HackerV1_14:: @ 0x08373B70
Str_10D0:
.if ENGLISH
	.string "I can turn\n"
	.string "foes into\n"
	.string "Mettaurs.$"
.else
	.string "とくていのザコテキを\n"
	.string "メットールにかえるのが\n"
	.string "ボクのしごとなんだ！$"
.endif

Text_HackerV1_15:: @ 0x08373B92
Str_10F2:
.if ENGLISH
	.string "I'll turn\n"
	.string "foes into\n"
	.string "Mettaurs.$"
.else
	.string "とくていのザコテキを\n"
	.string "メットールにしたい時は\n"
	.string "ボクを呼び出してね$"
.endif

Text_HackerV1_16:: @ 0x08373BB6
Str_1116:
.if ENGLISH
	.string "I turn foes\n"
	.string "into\n"
	.string "Mettaurs.$"
.else
	.string "とくていのザコテキを\n"
	.string "メットールにかえたい時は\n"
	.string "ボクのでばんさ！$"
.endif

Text_HackerV1_17:: @ 0x08373BD8
Str_1138:
.if ENGLISH
	.string "Enemies\n"
	.string "will become\n"
	.string "Mettaurs.$"
.else
	.string "ボクの力があれば\n"
	.string "とくていのザコテキなんて\n"
	.string "メットールにヘンシンさ！$"
.endif

Text_HackerV1_18:: @ 0x08373BFC
Str_115C:
.if ENGLISH
	.string "I destroy\n"
	.string "all small\n"
	.string "enemies!$"
.else
	.string "ザコテキどもは\n"
	.string "オレの力で\n"
	.string "いなくしてやるぜ！$"
.endif

Text_HackerV1_19:: @ 0x08373C15
Str_1175:
.if ENGLISH
	.string "Use me to\n"
	.string "wipe out\n"
	.string "small foes!$"
.else
	.string "ザコテキなんて\n"
	.string "オレの手にかかれば\n"
	.string "イチコロさ！$"
.endif

Text_HackerV1_20:: @ 0x08373C2F
Str_118F:
.if ENGLISH
	.string "Knock out\n"
	.string "small foes\n"
	.string "instantly!$"
.else
	.string "ジャマなザコテキは\n"
	.string "このオレの力で\n"
	.string "消去してやるぜ！$"
.endif

Text_HackerV1_21:: @ 0x08373C4D
Str_11AD:
.if ENGLISH
	.string "Certain \n"
	.string "enemies\n"
	.string "get stunned.$"
.else
	.string "とくていのザコテキの\n"
	.string "時間を止めたけりゃ\n"
	.string "ボクにまかせな！$"
.endif

Text_HackerV1_22:: @ 0x08373C6E
Str_11CE:
.if ENGLISH
	.string "I can stun\n"
	.string "certain\n"
	.string "foes.$"
.else
	.string "ボクの力があれば\n"
	.string "とくていのザコテキの\n"
	.string "時間がストップするよ$"
.endif

Text_HackerV1_23:: @ 0x08373C90
Str_11F0:
.if ENGLISH
	.string "Some foes\n"
	.string "will get\n"
	.string "stunned!$"
.else
	.string "とくていのザコテキの\n"
	.string "時間を止めたいときは\n"
	.string "ボクの力を使ってよ！$"
.endif

Text_HackerV1_24:: @ 0x08373CB6
Str_1216:
.if ENGLISH
	.string "My job is to\n"
	.string "stun certain\n"
	.string "enemies!$"
.else
	.string "ボクのしごとは\n"
	.string "とくていのザコテキの\n"
	.string "時間を止めちゃうことさ$"
.endif

Text_HackerV1_25:: @ 0x08373CD8
Str_1238:
.if ENGLISH
	.string "It's my duty\n"
	.string "to stun\n"
	.string "some foes.$"
.else
	.string "ボクを呼んでくれたら\n"
	.string "とくていのザコテキの\n"
	.string "時間は止まるよ！$"
.endif

Text_HackerV1_26:: @ 0x08373CFB
Str_125B:
.if ENGLISH
	.string "My job is to\n"
	.string "cut a boss's\n"
	.string "vitality!$"
.else
	.string "オレの力は\n"
	.string "ボスの体力を1体だけ\n"
	.string "はんぶんにすることだ！$"
.endif

Text_HackerV1_27:: @ 0x08373D1C
Str_127C:
.if ENGLISH
	.string "I halve\n"
	.string "a boss's\n"
	.string "vitality!$"
.else
	.string "1体だけでいいなら\n"
	.string "ボスの体力を\n"
	.string "はんぶんにしてやろう！$"
.endif

Text_HackerV1_28:: @ 0x08373D3C
Str_129C:
.if ENGLISH
	.string "I will cut\n"
	.string "a boss's\n"
	.string "vitality!$"
.else
	.string "オレを呼び出せば\n"
	.string "ボスの体力は1体だけ\n"
	.string "はんぶんになるぜ$"
.endif

Text_HackerV1_29:: @ 0x08373D5E
Str_12BE:
.if ENGLISH
	.string "Become Lv.A\n"
	.string "during the\n"
	.string "mission.$"
.else
	.string "そのミッション中だけ\n"
	.string "ゼロのレベルを\n"
	.string "Aにしてあげるよ$"
.endif

Text_HackerV1_30:: @ 0x08373D7B
Str_12DB:
.if ENGLISH
	.string "Use me to\n"
	.string "boost you to\n"
	.string "Lv.A.$"
.else
	.string "ミッション中だけ\n"
	.string "レベルをAにしたいなら\n"
	.string "ボクが力をかすよ！$"
.endif

Text_HackerV1_31:: @ 0x08373D9C
Str_12FC:
.if ENGLISH
	.string "I'll boost\n"
	.string "you to\n"
	.string "level A.$"
.else
	.string "ミッション中だけ\n"
	.string "レベルをAに\n"
	.string "かえてあげられるよ$"
.endif

Text_HackerV1_32:: @ 0x08373DB7
Str_1317:
.if ENGLISH
	.string "My energies\n"
	.string "will boost\n"
	.string "you to Lv.A.$"
.else
	.string "ボクの力を使えば\n"
	.string "キミのレベルを\n"
	.string "ミッション中だけ\n"
	.string "Aにしてあげられるんだ$"
.endif

Text_HackerV1_33:: @ 0x08373DE0
Str_1340:
.if ENGLISH
	.string "Lv.A? Sure,\n"
	.string "but it will\n"
	.string "only last\n"
	.string "the mission!$"
.else
	.string "ミッション中しか\n"
	.string "コウカはないけど\n"
	.string "キミのレベルを\n"
	.string "Aにしてあげられるよ$"
.endif

Text_NurseV2_00:: @ 0x08373E06
Str_1366:
.if ENGLISH
	.string "Use my power\n"
	.string "to increase\n"
	.string "lives by 5!$"
.else
	.string "わたしの力で\n"
	.string "のこりにんずうを\n"
	.string "5人ふやしてあげるわ！$"
.endif

Text_NurseV2_01:: @ 0x08373E24
Str_1384:
.if ENGLISH
	.string "If you want\n"
	.string "5 more lives\n"
	.string "call on me!$"
.else
	.string "のこりにんずうを\n"
	.string "5人ふやしたいときは\n"
	.string "わたしが力をかすわよ！$"
.endif

Text_NurseV2_02:: @ 0x08373E46
Str_13A6:
.if ENGLISH
	.string "My energy\n"
	.string "can heal\n"
	.string "16 vitality.$"
.else
	.string "わたしはあなたの体力を\n"
	.string "16メモリかいふくさせる\n"
	.string "力があるのよ$"
.endif

Text_NurseV2_03:: @ 0x08373E69
Str_13C9:
.if ENGLISH
	.string "I heal 16\n"
	.string "vitality\n"
	.string "for you.$"
.else
	.string "わたしの力で\n"
	.string "あなたの体力を16メモリ\n"
	.string "かいふくしてあげましょう$"
.endif

Text_NurseV2_04:: @ 0x08373E8D
Str_13ED:
.if ENGLISH
	.string "Let me heal\n"
	.string "16 vitality\n"
	.string "for you.$"
.else
	.string "16メモリ\n"
	.string "あなたの体力を\n"
	.string "かいふくしてあげるよ$"
.endif

Text_NurseV2_05:: @ 0x08373EA8
Str_1408:
.if ENGLISH
	.string "Wounded?\n"
	.string "I can heal\n"
	.string "16 vitality.$"
.else
	.string "体力がへったときは\n"
	.string "わたしが16メモリ\n"
	.string "かいふくしてあげる$"
.endif

Text_NurseV2_06:: @ 0x08373EC8
Str_1428:
.if ENGLISH
	.string "If you get\n"
	.string "hurt, I heal\n"
	.string "16 vitality.$"
.else
	.string "体力がへってきたら\n"
	.string "わたしが16メモリ\n"
	.string "かいふくしてあげるよ$"
.endif

Text_NurseV2_07:: @ 0x08373EE9
Str_1449:
.if ENGLISH
	.string "Use me when\n"
	.string "you need\n"
	.string "16 vitality!$"
.else
	.string "体力を16メモリ\n"
	.string "かいふくしたいときは\n"
	.string "わたしの力を使って！$"
.endif

Text_NurseV2_08:: @ 0x08373F0C
Str_146C:
.if ENGLISH
	.string "My powers\n"
	.string "can heal\n"
	.string "16 vitality.$"
.else
	.string "わたしの力を使えば\n"
	.string "あなたの体力を16メモリ\n"
	.string "かいふくできるわ$"
.endif

Text_NurseV2_09:: @ 0x08373F30
Str_1490:
.if ENGLISH
	.string "Just for\n"
	.string "you, I heal\n"
	.string "16 vitality.$"
.else
	.string "あなたのためなら\n"
	.string "体力を16メモリ\n"
	.string "かいふくしてあげるよ…$"
.endif

Text_NurseV2_10:: @ 0x08373F50
Str_14B0:
.if ENGLISH
	.string "I can heal\n"
	.string "all of your\n"
	.string "vitality\n"
	.string "and 1 tank!$"
.else
	.string "あんたの体力と\n"
	.string "サブタンク1こなんて\n"
	.string "わたしの力で\n"
	.string "いっきにマンタンさ！$"
.endif

Text_NurseV2_11:: @ 0x08373F78
Str_14D8:
.if ENGLISH
	.string "I can heal\n"
	.string "all vitality\n"
	.string "and 1 tank!$"
.else
	.string "体力とサブタンク1つを\n"
	.string "マンタンにしたいのなら\n"
	.string "わたしの力を使いなよ！$"
.endif

Text_NurseV2_12:: @ 0x08373FA0
Str_1500:
.if ENGLISH
	.string "Let me heal\n"
	.string "all of your\n"
	.string "vitality\n"
	.string "and 1 tank.$"
.else
	.string "あんたの体力と\n"
	.string "サブタンク1つくらい\n"
	.string "このわたしがすぐに\n"
	.string "マンタンにしてあげるよ$"
.endif

Text_NurseV2_13:: @ 0x08373FCB
Str_152B:
.if ENGLISH
	.string "Let me help!\n"
	.string "I heal all\n"
	.string "vitality\n"
	.string "and 1 tank!$"
.else
	.string "もし体力と\n"
	.string "サブタンク1つを\n"
	.string "マンタンにしたけりゃ\n"
	.string "わたしにまかせなよ！$"
.endif

Text_NurseV2_14:: @ 0x08373FF2
Str_1552:
.if ENGLISH
	.string "It's my job\n"
	.string "to heal you\n"
	.string "and 1 tank\n"
	.string "completely!$"
.else
	.string "あんたの体力と\n"
	.string "サブタンク1つを\n"
	.string "マンタンにすることが\n"
	.string "わたしのしごとさ！$"
.endif

Text_NurseV2_15:: @ 0x0837401A
Str_157A:
.if ENGLISH
	.string "My powers\n"
	.string "can heal you\n"
	.string "and 1 tank\n"
	.string "completely.$"
.else
	.string "わたしの力を使えば\n"
	.string "あんたの体力と\n"
	.string "サブタンク1つくらい\n"
	.string "すぐにマンタンにできるよ$"
.endif

Text_NurseV2_16:: @ 0x08374048
Str_15A8:
.if ENGLISH
	.string "Damage down.\n"
	.string "Bullets into\n"
	.string "2 vitality.$"
.else
	.string "ダメージげんてんするけど\n"
	.string "テキのエネルギーだんを\n"
	.string "体力2メモリにかえるよ$"
.endif

Text_NurseV2_17:: @ 0x0837406F
Str_15CF:
.if ENGLISH
	.string "Damage down.\n"
	.string "Bullets into\n"
	.string "2 vitality.$"
.else
	.string "テキのエネルギーだんを\n"
	.string "体力2メモリにかえるけど\n"
	.string "ダメージげんてんはあるよ$"
.endif

Text_NurseV2_18:: @ 0x08374097
Str_15F7:
.if ENGLISH
	.string "I drop Life\n"
	.string "Energy (S)\n"
	.string "faster!$"
.else
	.string "少しだけ はやく\n"
	.string "ライフエネルギーの小を\n"
	.string "ばらまいてあげるよ！$"
.endif

Text_NurseV2_19:: @ 0x083740B9
Str_1619:
.if ENGLISH
	.string "I scatter\n"
	.string "Life Energy\n"
	.string "(S) faster!$"
.else
	.string "少しだけ はやく\n"
	.string "ライフエネルギーの小を\n"
	.string "おとしてあげるよ！$"
.endif

# size: 59 bytes
Text_AnimalV2_00:: @ 0x083740da
Str_163A:
.if ENGLISH
	.string "I'll shoot\n"
	.string "your enemies\n"
	.string "to help you!$"
.else
	.string "ボクはテキに向けて\n"
	.string "タマをうって\n"
	.string "キミをえんごするよ！$"
.endif

Text_AnimalV2_01::
Str_1657:
.if ENGLISH
	.string "My bullets\n"
	.string "will pick\n"
	.string "off enemies!$"
.else
	.string "ボクのハッシャする\n"
	.string "タマは テキをねらって\n"
	.string "とんでいくよ！$"
.endif

# size: 42 bytes
Text_HackerV2_00:: @ 0x08374115
Str_1675:
.if ENGLISH
	.string "Block shots\n"
	.string "and you'll\n"
	.string "get EC (L)\n"
	.string "sometimes.$"
.else
	.string "エネルギーだんを\n"
	.string "シールドでタイミングよく\n"
	.string "ふせぐと たまに\n"
	.string "ECの大が出るよ$"
.endif
