Text_NurseV1_00:: @ 0x083734C9
	.string "わたくしの力で\n"
	.string "あなたのライフを2倍に\n"
	.string "してさしあげましょう$"

Text_NurseV1_01:: @ 0x083734EA
	.string "わたしの力で\n"
	.string "あなたのライフゲージを\n"
	.string "少しだけふやしてあげる$"

Text_NurseV1_02:: @ 0x0837350B
	.string "ほんの少しだけど\n"
	.string "あなたのライフゲージを\n"
	.string "ふやしてあげられるの$"

Text_NurseV1_03:: @ 0x0837352C
	.string "少しだけライフゲージを\n"
	.string "ふやしたいのなら\n"
	.string "わたしの力をつかってね！$"

Text_NurseV1_04:: @ 0x08373550
	.string "ライフゲージを少し\n"
	.string "ふやしたいときは\n"
	.string "わたしにまかせて！$"

Text_NurseV1_05:: @ 0x0837356E
	.string "サブタンクにかわって\n"
	.string "あなたのことを\n"
	.string "助けてあげるわ$"

Text_NurseV1_06:: @ 0x0837358A
	.string "もしサブタンクが\n"
	.string "ひつようなときは\n"
	.string "わたしの力をかすわ！$"

Text_NurseV1_07:: @ 0x083735A8
	.string "わたしの力で\n"
	.string "のこりにんずうを\n"
	.string "3人ふやしてあげるわ！$"

Text_NurseV1_08:: @ 0x083735C6
	.string "のこりにんずうを\n"
	.string "3人ふやしたいときは\n"
	.string "わたしが力をかすわよ！$"

Text_NurseV1_09:: @ 0x083735E8
	.string "わたしはあなたの体力を\n"
	.string "8メモリかいふくさせる\n"
	.string "力があるのよ$"

Text_NurseV1_10:: @ 0x0837360A
	.string "わたしの力で\n"
	.string "あなたの体力を8メモリ\n"
	.string "かいふくしてあげましょう$"

Text_NurseV1_11:: @ 0x0837362D
	.string "8メモリだけ\n"
	.string "あなたの体力を\n"
	.string "かいふくしてあげるよ$"

Text_NurseV1_12:: @ 0x08373649
	.string "体力がへったときは\n"
	.string "わたしが8メモリ\n"
	.string "かいふくしてあげるね$"

Text_NurseV1_13:: @ 0x08373669
	.string "体力がへってきたら\n"
	.string "わたしが8メモリ\n"
	.string "かいふくしてあげるよ$"

Text_NurseV1_14:: @ 0x08373689
	.string "体力を8メモリ\n"
	.string "かいふくしたいときは\n"
	.string "わたしの力を使って！$"

Text_NurseV1_15:: @ 0x083736AB
	.string "わたしの力を使えば\n"
	.string "あなたの体力を8メモリ\n"
	.string "かいふくできるわ$"

Text_NurseV1_16:: @ 0x083736CE
	.string "あなたのためなら\n"
	.string "体力を8メモリ\n"
	.string "かいふくしてあげるよ…$"

Text_NurseV1_17:: @ 0x083736ED
	.string "あんたの体力なんて\n"
	.string "わたしの力で\n"
	.string "いっきにマンタンさ！$"

Text_NurseV1_18:: @ 0x0837370C
	.string "体力をマンタンに\n"
	.string "したいのなら\n"
	.string "わたしの力を使いなよ！$"

Text_NurseV1_19:: @ 0x0837372C
	.string "あんたの体力くらい\n"
	.string "このわたしがすぐに\n"
	.string "マンタンにしてあげるよ$"

Text_NurseV1_20:: @ 0x0837374E
	.string "もし体力を\n"
	.string "マンタンにしたけりゃ\n"
	.string "わたしにまかせなよ！$"

Text_NurseV1_21:: @ 0x0837376C
	.string "あんたの体力を\n"
	.string "マンタンにすることが\n"
	.string "わたしのしごとさ！$"

Text_NurseV1_22:: @ 0x0837378B
	.string "わたしの力を使えば\n"
	.string "あんたの体力くらい\n"
	.string "すぐにマンタンにできるよ$"

Text_NurseV1_23:: @ 0x083737B0
	.string "ダメージげんてんするけど\n"
	.string "テキのエネルギーだんを\n"
	.string "体力1メモリにかえるよ$"

Text_NurseV1_24:: @ 0x083737D7
	.string "テキのエネルギーだんを\n"
	.string "体力1メモリにかえるけど\n"
	.string "ダメージげんてんはあるよ$"

Text_NurseV1_25:: @ 0x083737FF
	.string "あなたのまわりに\n"
	.string "ライフエネルギーの小を\n"
	.string "ばらまいてあげるよ！$"

Text_NurseV1_26:: @ 0x08373820
	.string "わたしがとびまわって\n"
	.string "ライフエネルギーの小を\n"
	.string "おとしてあげるよ！$"

Text_AnimalV1_00:: @ 0x08373842
	.string "ふれるとミスになる\n"
	.string "トゲやマグマを\n"
	.string "ダメージにへんかんするよ$"

Text_AnimalV1_01:: @ 0x08373861
	.string "はしるはやさを少し\n"
	.string "はやくしたいのなら\n"
	.string "ボクにまかせてくれ！$"

Text_AnimalV1_02:: @ 0x08373881
	.string "わたしの力を使えば\n"
	.string "ハシゴをはやく\n"
	.string "のぼれるッキャ！$"

Text_AnimalV1_03:: @ 0x0837389E
	.string "ボクの力で\n"
	.string "かべからずりおちる\n"
	.string "そくどをおそくするよ！$"

Text_AnimalV1_04:: @ 0x083738BB
	.string "オイラの力は\n"
	.string "ダメージをうけたときの\n"
	.string "あとずさりをなくすことさ$"

Text_AnimalV1_05:: @ 0x083738DC
	.string "もしもキミが\n"
	.string "あなにおちたら\n"
	.string "ボクが助けてあげるよ$"

Text_AnimalV1_06:: @ 0x083738F7
	.string "ボクがそばにいれば\n"
	.string "キミがあなにおちても\n"
	.string "助けてあげられるよ！$"

Text_AnimalV1_07:: @ 0x08373918
	.string "とくていのテキに\n"
	.string "くっついて\n"
	.string "動けなくするのが\n"
	.string "ボクのやくめなんだ！$"

Text_AnimalV1_08:: @ 0x0837393C
	.string "ボクがとくていのテキに\n"
	.string "ピッタリくっついて\n"
	.string "動きを止めてあげる！$"

Text_AnimalV1_09:: @ 0x0837395F
	.string "ボクはまっすぐ\n"
	.string "タマをうって\n"
	.string "キミをえんごするよ！$"

Text_AnimalV1_10:: @ 0x08373979
	.string "ボクのハッシャする\n"
	.string "タマは まっすぐ\n"
	.string "とんでいくよ！$"

Text_AnimalV1_11:: @ 0x08373994
	.string "ボクのハッシャする\n"
	.string "タマは じめんに向かって\n"
	.string "とんでいくよ！$"

Text_AnimalV1_12:: @ 0x083739B4
	.string "ボクは じめんに向けて\n"
	.string "タマをハッシャする\n"
	.string "エルフだよ！$"

Text_HackerV1_00:: @ 0x083739D2
	.string "とったアイテムのりょうを\n"
	.string "2倍にしたいときは\n"
	.string "このボクが力をかすよ！$"

Text_HackerV1_01:: @ 0x083739F7
	.string "ザコテキをたおした時に\n"
	.string "かならず\n"
	.string "アイテムがでるのさ！$"

Text_HackerV1_02:: @ 0x08373A14
	.string "3だんぎりの時に上を\n"
	.string "おして セイバーをふると\n"
	.string "きりあげられるよ$"

Text_HackerV1_03:: @ 0x08373A37
	.string "3だんぎりの時に下を\n"
	.string "おして セイバーをふると\n"
	.string "ショウゲキハが出るよ$"

Text_HackerV1_04:: @ 0x08373A5D
	.string "バスターショットを\n"
	.string "4れんしゃにしたけりゃ\n"
	.string "ボクにまかせて！$"

Text_HackerV1_05:: @ 0x08373A7C
	.string "ダッシュ中に下か上\n"
	.string "ジャンプ中に上で\n"
	.string "かいてんぎりができるよ$"

Text_HackerV1_06:: @ 0x08373AA0
	.string "セイバーをふって\n"
	.string "テキのエネルギーだんを\n"
	.string "消すことができるよ$"

Text_HackerV1_07:: @ 0x08373AC0
	.string "エネルギーだんを\n"
	.string "シールドでタイミングよく\n"
	.string "ふせぐとECの小が出るよ$"

Text_HackerV1_08:: @ 0x08373AE5
	.string "バスターのパワーを\n"
	.string "プラス1するよ$"

Text_HackerV1_09:: @ 0x08373AF7
	.string "セイバーのパワーを\n"
	.string "プラス1するよ$"

Text_HackerV1_10:: @ 0x08373B09
	.string "ロッドのパワーを\n"
	.string "プラス1するよ$"

Text_HackerV1_11:: @ 0x08373B1A
	.string "シールドのパワーを\n"
	.string "プラス1するよ$"

Text_HackerV1_12:: @ 0x08373B2C
	.string "ブキをチャージする\n"
	.string "時間をもう少し\n"
	.string "はやくしてあげるよ$"

Text_HackerV1_13:: @ 0x08373B4B
	.string "とくていのザコテキなんて\n"
	.string "ボクの力でメットールに\n"
	.string "かえちゃうんだから！$"

Text_HackerV1_14:: @ 0x08373B70
	.string "とくていのザコテキを\n"
	.string "メットールにかえるのが\n"
	.string "ボクのしごとなんだ！$"

Text_HackerV1_15:: @ 0x08373B92
	.string "とくていのザコテキを\n"
	.string "メットールにしたい時は\n"
	.string "ボクを呼び出してね$"

Text_HackerV1_16:: @ 0x08373BB6
	.string "とくていのザコテキを\n"
	.string "メットールにかえたい時は\n"
	.string "ボクのでばんさ！$"

Text_HackerV1_17:: @ 0x08373BD8
	.string "ボクの力があれば\n"
	.string "とくていのザコテキなんて\n"
	.string "メットールにヘンシンさ！$"

Text_HackerV1_18:: @ 0x08373BFC
	.string "ザコテキどもは\n"
	.string "オレの力で\n"
	.string "いなくしてやるぜ！$"

Text_HackerV1_19:: @ 0x08373C15
	.string "ザコテキなんて\n"
	.string "オレの手にかかれば\n"
	.string "イチコロさ！$"

Text_HackerV1_20:: @ 0x08373C2F
	.string "ジャマなザコテキは\n"
	.string "このオレの力で\n"
	.string "消去してやるぜ！$"

Text_HackerV1_21:: @ 0x08373C4D
	.string "とくていのザコテキの\n"
	.string "時間を止めたけりゃ\n"
	.string "ボクにまかせな！$"

Text_HackerV1_22:: @ 0x08373C6E
	.string "ボクの力があれば\n"
	.string "とくていのザコテキの\n"
	.string "時間がストップするよ$"

Text_HackerV1_23:: @ 0x08373C90
	.string "とくていのザコテキの\n"
	.string "時間を止めたいときは\n"
	.string "ボクの力を使ってよ！$"

Text_HackerV1_24:: @ 0x08373CB6
	.string "ボクのしごとは\n"
	.string "とくていのザコテキの\n"
	.string "時間を止めちゃうことさ$"

Text_HackerV1_25:: @ 0x08373CD8
	.string "ボクを呼んでくれたら\n"
	.string "とくていのザコテキの\n"
	.string "時間は止まるよ！$"

Text_HackerV1_26:: @ 0x08373CFB
	.string "オレの力は\n"
	.string "ボスの体力を1体だけ\n"
	.string "はんぶんにすることだ！$"

Text_HackerV1_27:: @ 0x08373D1C
	.string "1体だけでいいなら\n"
	.string "ボスの体力を\n"
	.string "はんぶんにしてやろう！$"

Text_HackerV1_28:: @ 0x08373D3C
	.string "オレを呼び出せば\n"
	.string "ボスの体力は1体だけ\n"
	.string "はんぶんになるぜ$"

Text_HackerV1_29:: @ 0x08373D5E
	.string "そのミッション中だけ\n"
	.string "ゼロのレベルを\n"
	.string "Aにしてあげるよ$"

Text_HackerV1_30:: @ 0x08373D7B
	.string "ミッション中だけ\n"
	.string "レベルをAにしたいなら\n"
	.string "ボクが力をかすよ！$"

Text_HackerV1_31:: @ 0x08373D9C
	.string "ミッション中だけ\n"
	.string "レベルをAに\n"
	.string "かえてあげられるよ$"

Text_HackerV1_32:: @ 0x08373DB7
	.string "ボクの力を使えば\n"
	.string "キミのレベルを\n"
	.string "ミッション中だけ\n"
	.string "Aにしてあげられるんだ$"

Text_HackerV1_33:: @ 0x08373DE0
	.string "ミッション中しか\n"
	.string "コウカはないけど\n"
	.string "キミのレベルを\n"
	.string "Aにしてあげられるよ$"

Text_NurseV2_00:: @ 0x08373E06
	.string "わたしの力で\n"
	.string "のこりにんずうを\n"
	.string "5人ふやしてあげるわ！$"

Text_NurseV2_01:: @ 0x08373E24
	.string "のこりにんずうを\n"
	.string "5人ふやしたいときは\n"
	.string "わたしが力をかすわよ！$"

Text_NurseV2_02:: @ 0x08373E46
	.string "わたしはあなたの体力を\n"
	.string "16メモリかいふくさせる\n"
	.string "力があるのよ$"

Text_NurseV2_03:: @ 0x08373E69
	.string "わたしの力で\n"
	.string "あなたの体力を16メモリ\n"
	.string "かいふくしてあげましょう$"

Text_NurseV2_04:: @ 0x08373E8D
	.string "16メモリ\n"
	.string "あなたの体力を\n"
	.string "かいふくしてあげるよ$"

Text_NurseV2_05:: @ 0x08373EA8
	.string "体力がへったときは\n"
	.string "わたしが16メモリ\n"
	.string "かいふくしてあげる$"

Text_NurseV2_06:: @ 0x08373EC8
	.string "体力がへってきたら\n"
	.string "わたしが16メモリ\n"
	.string "かいふくしてあげるよ$"

Text_NurseV2_07:: @ 0x08373EE9
	.string "体力を16メモリ\n"
	.string "かいふくしたいときは\n"
	.string "わたしの力を使って！$"

Text_NurseV2_08:: @ 0x08373F0C
	.string "わたしの力を使えば\n"
	.string "あなたの体力を16メモリ\n"
	.string "かいふくできるわ$"

Text_NurseV2_09:: @ 0x08373F30
	.string "あなたのためなら\n"
	.string "体力を16メモリ\n"
	.string "かいふくしてあげるよ…$"

Text_NurseV2_10:: @ 0x08373F50
	.string "あんたの体力と\n"
	.string "サブタンク1こなんて\n"
	.string "わたしの力で\n"
	.string "いっきにマンタンさ！$"

Text_NurseV2_11:: @ 0x08373F78
	.string "体力とサブタンク1つを\n"
	.string "マンタンにしたいのなら\n"
	.string "わたしの力を使いなよ！$"

Text_NurseV2_12:: @ 0x08373FA0
	.string "あんたの体力と\n"
	.string "サブタンク1つくらい\n"
	.string "このわたしがすぐに\n"
	.string "マンタンにしてあげるよ$"

Text_NurseV2_13:: @ 0x08373FCB
	.string "もし体力と\n"
	.string "サブタンク1つを\n"
	.string "マンタンにしたけりゃ\n"
	.string "わたしにまかせなよ！$"

Text_NurseV2_14:: @ 0x08373FF2
	.string "あんたの体力と\n"
	.string "サブタンク1つを\n"
	.string "マンタンにすることが\n"
	.string "わたしのしごとさ！$"

Text_NurseV2_15:: @ 0x0837401A
	.string "わたしの力を使えば\n"
	.string "あんたの体力と\n"
	.string "サブタンク1つくらい\n"
	.string "すぐにマンタンにできるよ$"

Text_NurseV2_16:: @ 0x08374048
	.string "ダメージげんてんするけど\n"
	.string "テキのエネルギーだんを\n"
	.string "体力2メモリにかえるよ$"

Text_NurseV2_17:: @ 0x0837406F
	.string "テキのエネルギーだんを\n"
	.string "体力2メモリにかえるけど\n"
	.string "ダメージげんてんはあるよ$"

Text_NurseV2_18:: @ 0x08374097
	.string "少しだけ はやく\n"
	.string "ライフエネルギーの小を\n"
	.string "ばらまいてあげるよ！$"

Text_NurseV2_19:: @ 0x083740B9
	.string "少しだけ はやく\n"
	.string "ライフエネルギーの小を\n"
	.string "おとしてあげるよ！$"

# size: 59 bytes
Text_AnimalV2_00:: @ 0x083740da
	.string "ボクはテキに向けて\n"
	.string "タマをうって\n"
	.string "キミをえんごするよ！$"

Text_AnimalV2_01::
	.string "ボクのハッシャする\n"
	.string "タマは テキをねらって\n"
	.string "とんでいくよ！$"

# size: 42 bytes
Text_HackerV2_00:: @ 0x08374115
	.string "エネルギーだんを\n"
	.string "シールドでタイミングよく\n"
	.string "ふせぐと たまに\n"
	.string "ECの大が出るよ$"
