Str_34BE:
.if ENGLISH
  .string "{RED}000{RED_END}$"
.else
.string "{RED}000{RED_END}$"
.endif
Str_34C4:
.if ENGLISH
  .string "{RED}001{RED_END}$"
.else
.string "{RED}001{RED_END}$"
.endif
Str_34CA:
.if ENGLISH
  .string "{RED}002{RED_END}$"
.else
.string "{RED}002{RED_END}$"
.endif
Str_34D0:
.if ENGLISH
  .string "{RED}003{RED_END}$"
.else
.string "{RED}003{RED_END}$"
.endif
Str_34D6:
.if ENGLISH
  .string "{RED}004{RED_END}$"
.else
.string "{RED}004{RED_END}$"
.endif
Str_34DC:
.if ENGLISH
  .string "{RED}005{RED_END}$"
.else
.string "{RED}005{RED_END}$"
.endif
Str_34E2:
.if ENGLISH
  .string "{RED}006{RED_END}$"
.else
.string "{RED}006{RED_END}$"
.endif
Str_34E8:
.if ENGLISH
  .string "{RED}007{RED_END}$"
.else
.string "{RED}007{RED_END}$"
.endif
Str_34EE:
.if ENGLISH
  .string "{RED}008{RED_END}$"
.else
.string "{RED}008{RED_END}$"
.endif
Str_34F4:
.if ENGLISH
  .string "{RED}009{RED_END}$"
.else
.string "{RED}009{RED_END}$"
.endif
Str_34FA:
.if ENGLISH
  .string "{RED}010{RED_END}$"
.else
.string "{RED}010{RED_END}$"
.endif
Str_3500:
.if ENGLISH
  .string "{RED}011{RED_END}$"
.else
.string "{RED}011{RED_END}$"
.endif
Str_3506:
.if ENGLISH
  .string "{RED}012{RED_END}$"
.else
.string "{RED}012{RED_END}$"
.endif
Str_350C:
.if ENGLISH
  .string "{RED}013{RED_END}$"
.else
.string "{RED}013{RED_END}$"
.endif
Str_3512:
.if ENGLISH
  .string "{RED}014{RED_END}$"
.else
.string "{RED}014{RED_END}$"
.endif
Str_3518:
.if ENGLISH
  .string "{RED}015{RED_END}$"
.else
.string "{RED}015{RED_END}$"
.endif
Str_351E:
.if ENGLISH
  .string "{RED}016{RED_END}$"
.else
.string "{RED}016{RED_END}$"
.endif
Str_3524:
.if ENGLISH
  .string "{RED}017{RED_END}$"
.else
.string "{RED}017{RED_END}$"
.endif
Str_352A:
.if ENGLISH
  .string "{RED}018{RED_END}$"
.else
.string "{RED}018{RED_END}$"
.endif
Str_3530:
.if ENGLISH
  .string "{RED}019{RED_END}$"
.else
.string "{RED}019{RED_END}$"
.endif
Str_3536:
.if ENGLISH
  .string "{RED}020{RED_END}$"
.else
.string "{RED}020{RED_END}$"
.endif
Str_353C:
.if ENGLISH
  .string "{RED}021{RED_END}$"
.else
.string "{RED}021{RED_END}$"
.endif
Str_3542:
.if ENGLISH
  .string "{RED}022{RED_END}$"
.else
.string "{RED}022{RED_END}$"
.endif
Str_3548:
.if ENGLISH
  .string "{RED}023{RED_END}$"
.else
.string "{RED}023{RED_END}$"
.endif
Str_354E:
.if ENGLISH
  .string "{RED}024{RED_END}$"
.else
.string "{RED}024{RED_END}$"
.endif
Str_3554:
.if ENGLISH
  .string "{RED}025{RED_END}$"
.else
.string "{RED}025{RED_END}$"
.endif
Str_355A:
.if ENGLISH
  .string "{RED}026{RED_END}$"
.else
.string "{RED}026{RED_END}$"
.endif
Str_3560:
.if ENGLISH
  .string "{RED}027{RED_END}$"
.else
.string "{RED}027{RED_END}$"
.endif
Str_3566:
.if ENGLISH
  .string "{RED}028{RED_END}$"
.else
.string "{RED}028{RED_END}$"
.endif
Str_356C:
.if ENGLISH
  .string "{RED}029{RED_END}$"
.else
.string "{RED}029{RED_END}$"
.endif
Str_3572:
.if ENGLISH
  .string "{RED}030{RED_END}$"
.else
.string "{RED}030{RED_END}$"
.endif
Str_3578:
.if ENGLISH
  .string "{RED}031{RED_END}$"
.else
.string "{RED}031{RED_END}$"
.endif
Str_357E:
.if ENGLISH
  .string "{RED}032{RED_END}$"
.else
.string "{RED}032{RED_END}$"
.endif
Str_3584:
.if ENGLISH
  .string "{RED}033{RED_END}$"
.else
.string "{RED}033{RED_END}$"
.endif
Str_358A:
.if ENGLISH
  .string "{RED}034{RED_END}$"
.else
.string "{RED}034{RED_END}$"
.endif
Str_3590:
.if ENGLISH
  .string "{RED}035{RED_END}$"
.else
.string "{RED}035{RED_END}$"
.endif
Str_3596:
.if ENGLISH
  .string "{RED}036{RED_END}$"
.else
.string "{RED}036{RED_END}$"
.endif
Str_359C:
.if ENGLISH
  .string "{RED}037{RED_END}$"
.else
.string "{RED}037{RED_END}$"
.endif
Str_35A2:
.if ENGLISH
  .string "{RED}038{RED_END}$"
.else
.string "{RED}038{RED_END}$"
.endif
Str_35A8:
.if ENGLISH
  .string "{RED}039{RED_END}$"
.else
.string "{RED}039{RED_END}$"
.endif
Str_35AE:
.if ENGLISH
  .string "{RED}040{RED_END}$"
.else
.string "{RED}040{RED_END}$"
.endif
Str_35B4:
.if ENGLISH
  .string "{RED}041{RED_END}$"
.else
.string "{RED}041{RED_END}$"
.endif
Str_35BA:
.if ENGLISH
  .string "{RED}042{RED_END}$"
.else
.string "{RED}042{RED_END}$"
.endif
Str_35C0:
.if ENGLISH
  .string "{RED}043{RED_END}$"
.else
.string "{RED}043{RED_END}$"
.endif
Str_35C6:
.if ENGLISH
  .string "{RED}044{RED_END}$"
.else
.string "{RED}044{RED_END}$"
.endif
Str_35CC:
.if ENGLISH
  .string "{RED}045{RED_END}$"
.else
.string "{RED}045{RED_END}$"
.endif
Str_35D2:
.if ENGLISH
  .string "{RED}046{RED_END}$"
.else
.string "{RED}046{RED_END}$"
.endif
Str_35D8:
.if ENGLISH
  .string "{RED}047{RED_END}$"
.else
.string "{RED}047{RED_END}$"
.endif
Str_35DE:
.if ENGLISH
  .string "{RED}048{RED_END}$"
.else
.string "{RED}048{RED_END}$"
.endif
Str_35E4:
.if ENGLISH
  .string "{RED}049{RED_END}$"
.else
.string "{RED}049{RED_END}$"
.endif
Str_35EA:
.if ENGLISH
  .string "{RED}050{RED_END}$"
.else
.string "{RED}050{RED_END}$"
.endif
Str_35F0:
.if ENGLISH
  .string "{RED}051{RED_END}$"
.else
.string "{RED}051{RED_END}$"
.endif
Str_35F6:
.if ENGLISH
  .string "{RED}052{RED_END}$"
.else
.string "{RED}052{RED_END}$"
.endif
Str_35FC:
.if ENGLISH
  .string "{RED}053{RED_END}$"
.else
.string "{RED}053{RED_END}$"
.endif
Str_3602:
.if ENGLISH
  .string "{RED}054{RED_END}$"
.else
.string "{RED}054{RED_END}$"
.endif
Str_3608:
.if ENGLISH
  .string "{RED}055{RED_END}$"
.else
.string "{RED}055{RED_END}$"
.endif
Str_360E:
.if ENGLISH
  .string "{RED}056{RED_END}$"
.else
.string "{RED}056{RED_END}$"
.endif
Str_3614:
.if ENGLISH
  .string "{RED}057{RED_END}$"
.else
.string "{RED}057{RED_END}$"
.endif
Str_361A:
.if ENGLISH
  .string "{RED}058{RED_END}$"
.else
.string "{RED}058{RED_END}$"
.endif
Str_3620:
.if ENGLISH
  .string "{RED}059{RED_END}$"
.else
.string "{RED}059{RED_END}$"
.endif
Str_3626:
.if ENGLISH
  .string "{RED}060{RED_END}$"
.else
.string "{RED}060{RED_END}$"
.endif
Str_362C:
.if ENGLISH
  .string "{RED}061{RED_END}$"
.else
.string "{RED}061{RED_END}$"
.endif
Str_3632:
.if ENGLISH
  .string "{RED}062{RED_END}$"
.else
.string "{RED}062{RED_END}$"
.endif
Str_3638:
.if ENGLISH
  .string "{RED}063{RED_END}$"
.else
.string "{RED}063{RED_END}$"
.endif
Str_363E:
.if ENGLISH
  .string "{RED}064{RED_END}$"
.else
.string "{RED}064{RED_END}$"
.endif
Str_3644:
.if ENGLISH
  .string "{RED}065{RED_END}$"
.else
.string "{RED}065{RED_END}$"
.endif
Str_364A:
.if ENGLISH
  .string "{RED}066{RED_END}$"
.else
.string "{RED}066{RED_END}$"
.endif
Str_3650:
.if ENGLISH
  .string "{RED}067{RED_END}$"
.else
.string "{RED}067{RED_END}$"
.endif
Str_3656:
.if ENGLISH
  .string "{RED}068{RED_END}$"
.else
.string "{RED}068{RED_END}$"
.endif
Str_365C:
.if ENGLISH
  .string "{RED}069{RED_END}$"
.else
.string "{RED}069{RED_END}$"
.endif
Str_3662:
.if ENGLISH
  .string "{RED}070{RED_END}$"
.else
.string "{RED}070{RED_END}$"
.endif
Str_3668:
.if ENGLISH
  .string "{RED}071{RED_END}$"
.else
.string "{RED}071{RED_END}$"
.endif
Str_366E:
.if ENGLISH
  .string "{RED}072{RED_END}$"
.else
.string "{RED}072{RED_END}$"
.endif
Str_3674:
.if ENGLISH
  .string "{RED}073{RED_END}$"
.else
.string "{RED}073{RED_END}$"
.endif
Str_367A:
.if ENGLISH
  .string "{RED}074{RED_END}$"
.else
.string "{RED}074{RED_END}$"
.endif
Str_3680:
.if ENGLISH
  .string "{RED}075{RED_END}$"
.else
.string "{RED}075{RED_END}$"
.endif
Str_3686:
.if ENGLISH
  .string "{RED}076{RED_END}$"
.else
.string "{RED}076{RED_END}$"
.endif
Str_368C:
.if ENGLISH
  .string "{RED}077{RED_END}$"
.else
.string "{RED}077{RED_END}$"
.endif
Str_3692:
.if ENGLISH
  .string "{RED}078{RED_END}$"
.else
.string "{RED}078{RED_END}$"
.endif
Str_3698:
.if ENGLISH
  .string "{RED}079{RED_END}$"
.else
.string "{RED}079{RED_END}$"
.endif
Str_369E:
.if ENGLISH
  .string "{RED}080{RED_END}$"
.else
.string "{RED}080{RED_END}$"
.endif
Str_36A4:
.if ENGLISH
  .string "{RED}081{RED_END}$"
.else
.string "{RED}081{RED_END}$"
.endif
Str_36AA:
.if ENGLISH
  .string "{RED}082{RED_END}$"
.else
.string "{RED}082{RED_END}$"
.endif
Str_36B0:
.if ENGLISH
  .string "{RED}083{RED_END}$"
.else
.string "{RED}083{RED_END}$"
.endif
Str_36B6:
.if ENGLISH
  .string "{RED}084{RED_END}$"
.else
.string "{RED}084{RED_END}$"
.endif
Str_36BC:
.if ENGLISH
  .string "{RED}085{RED_END}$"
.else
.string "{RED}085{RED_END}$"
.endif
Str_36C2:
.if ENGLISH
  .string "{RED}086{RED_END}$"
.else
.string "{RED}086{RED_END}$"
.endif
Str_36C8:
.if ENGLISH
  .string "{RED}087{RED_END}$"
.else
.string "{RED}087{RED_END}$"
.endif
Str_36CE:
.if ENGLISH
  .string "{RED}088{RED_END}$"
.else
.string "{RED}088{RED_END}$"
.endif
Str_36D4:
.if ENGLISH
  .string "{RED}089{RED_END}$"
.else
.string "{RED}089{RED_END}$"
.endif
Str_36DA:
.if ENGLISH
  .string "{RED}090{RED_END}$"
.else
.string "{RED}090{RED_END}$"
.endif
Str_36E0:
.if ENGLISH
  .string "{RED}091{RED_END}$"
.else
.string "{RED}091{RED_END}$"
.endif
Str_36E6:
.if ENGLISH
  .string "{RED}092{RED_END}$"
.else
.string "{RED}092{RED_END}$"
.endif
Str_36EC:
.if ENGLISH
  .string "{RED}093{RED_END}$"
.else
.string "{RED}093{RED_END}$"
.endif
Str_36F2:
.if ENGLISH
  .string "{RED}094{RED_END}$"
.else
.string "{RED}094{RED_END}$"
.endif
Str_36F8:
.if ENGLISH
  .string "{RED}095{RED_END}$"
.else
.string "{RED}095{RED_END}$"
.endif
Str_36FE:
.if ENGLISH
  .string "{RED}096{RED_END}$"
.else
.string "{RED}096{RED_END}$"
.endif
Str_3704:
.if ENGLISH
  .string "{RED}097{RED_END}$"
.else
.string "{RED}097{RED_END}$"
.endif
Str_370A:
.if ENGLISH
  .string "{RED}098{RED_END}$"
.else
.string "{RED}098{RED_END}$"
.endif
Str_3710:
.if ENGLISH
  .string "{RED}099{RED_END}$"
.else
.string "{RED}099{RED_END}$"
.endif
Str_3716:
.if ENGLISH
  .string "{RED}100{RED_END}$"
.else
.string "{RED}100{RED_END}$"
.endif
Str_371C:
.if ENGLISH
  .string "{RED}101{RED_END}$"
.else
.string "{RED}101{RED_END}$"
.endif
Str_3722:
.if ENGLISH
  .string "{RED}102{RED_END}$"
.else
.string "{RED}102{RED_END}$"
.endif
Str_3728:
.if ENGLISH
  .string "{RED}103{RED_END}$"
.else
.string "{RED}103{RED_END}$"
.endif
Str_372E:
.if ENGLISH
  .string "{RED}104{RED_END}$"
.else
.string "{RED}104{RED_END}$"
.endif
Str_3734:
.if ENGLISH
  .string "{RED}105{RED_END}$"
.else
.string "{RED}105{RED_END}$"
.endif
Str_373A:
.if ENGLISH
  .string "{RED}106{RED_END}$"
.else
.string "{RED}106{RED_END}$"
.endif
Str_3740:
.if ENGLISH
  .string "{RED}107{RED_END}$"
.else
.string "{RED}107{RED_END}$"
.endif
Str_3746:
.if ENGLISH
  .string "{RED}108{RED_END}$"
.else
.string "{RED}108{RED_END}$"
.endif
Str_374C:
.if ENGLISH
  .string "{RED}109{RED_END}$"
.else
.string "{RED}109{RED_END}$"
.endif
Str_3752:
.if ENGLISH
  .string "{RED}110{RED_END}$"
.else
.string "{RED}110{RED_END}$"
.endif
Str_3758:
.if ENGLISH
  .string "{RED}111{RED_END}$"
.else
.string "{RED}111{RED_END}$"
.endif
Str_375E:
.if ENGLISH
  .string "{RED}112{RED_END}$"
.else
.string "{RED}112{RED_END}$"
.endif
Str_3764:
.if ENGLISH
  .string "{RED}113{RED_END}$"
.else
.string "{RED}113{RED_END}$"
.endif
Str_376A:
.if ENGLISH
  .string "{RED}114{RED_END}$"
.else
.string "{RED}114{RED_END}$"
.endif
Str_3770:
.if ENGLISH
  .string "{RED}115{RED_END}$"
.else
.string "{RED}115{RED_END}$"
.endif
Str_3776:
.if ENGLISH
  .string "{RED}116{RED_END}$"
.else
.string "{RED}116{RED_END}$"
.endif
Str_377C:
.if ENGLISH
  .string "{RED}117{RED_END}$"
.else
.string "{RED}117{RED_END}$"
.endif
Str_3782:
.if ENGLISH
  .string "{RED}118{RED_END}$"
.else
.string "{RED}118{RED_END}$"
.endif
Str_3788:
.if ENGLISH
  .string "{RED}119{RED_END}$"
.else
.string "{RED}119{RED_END}$"
.endif
Str_378E:
.if ENGLISH
  .string "{RED}120{RED_END}$"
.else
.string "{RED}120{RED_END}$"
.endif
Str_3794:
.if ENGLISH
  .string "{RED}121{RED_END}$"
.else
.string "{RED}121{RED_END}$"
.endif
Str_379A:
.if ENGLISH
  .string "{RED}122{RED_END}$"
.else
.string "{RED}122{RED_END}$"
.endif
Str_37A0:
.if ENGLISH
  .string "{RED}123{RED_END}$"
.else
.string "{RED}123{RED_END}$"
.endif
Str_37A6:
.if ENGLISH
  .string "{RED}124{RED_END}$"
.else
.string "{RED}124{RED_END}$"
.endif
Str_37AC:
.if ENGLISH
  .string "{RED}125{RED_END}$"
.else
.string "{RED}125{RED_END}$"
.endif
Str_37B2:
.if ENGLISH
  .string "{RED}126{RED_END}$"
.else
.string "{RED}126{RED_END}$"
.endif
Str_37B8:
.if ENGLISH
  .string "{RED}127{RED_END}$"
.else
.string "{RED}127{RED_END}$"
.endif
Str_37BE:
.if ENGLISH
  .string "{RED}128{RED_END}$"
.else
.string "{RED}128{RED_END}$"
.endif
Str_37C4:
.if ENGLISH
  .string "{RED}129{RED_END}$"
.else
.string "{RED}129{RED_END}$"
.endif
Str_37CA:
.if ENGLISH
  .string "{RED}130{RED_END}$"
.else
.string "{RED}130{RED_END}$"
.endif
Str_37D0:
.if ENGLISH
  .string "{RED}131{RED_END}$"
.else
.string "{RED}131{RED_END}$"
.endif
Str_37D6:
.if ENGLISH
  .string "{RED}132{RED_END}$"
.else
.string "{RED}132{RED_END}$"
.endif
Str_37DC:
.if ENGLISH
  .string "{RED}133{RED_END}$"
.else
.string "{RED}133{RED_END}$"
.endif
Str_37E2:
.if ENGLISH
  .string "{RED}134{RED_END}$"
.else
.string "{RED}134{RED_END}$"
.endif
Str_37E8:
.if ENGLISH
  .string "{RED}135{RED_END}$"
.else
.string "{RED}135{RED_END}$"
.endif
Str_37EE:
.if ENGLISH
  .string "{RED}136{RED_END}$"
.else
.string "{RED}136{RED_END}$"
.endif
Str_37F4:
.if ENGLISH
  .string "{RED}137{RED_END}$"
.else
.string "{RED}137{RED_END}$"
.endif
Str_37FA:
.if ENGLISH
  .string "{RED}138{RED_END}$"
.else
.string "{RED}138{RED_END}$"
.endif
Str_3800:
.if ENGLISH
  .string "{RED}139{RED_END}$"
.else
.string "{RED}139{RED_END}$"
.endif
Str_3806:
.if ENGLISH
  .string "{RED}140{RED_END}$"
.else
.string "{RED}140{RED_END}$"
.endif
Str_380C:
.if ENGLISH
  .string "{RED}141{RED_END}$"
.else
.string "{RED}141{RED_END}$"
.endif
Str_3812:
.if ENGLISH
  .string "{RED}142{RED_END}$"
.else
.string "{RED}142{RED_END}$"
.endif
Str_3818:
.if ENGLISH
  .string "{RED}143{RED_END}$"
.else
.string "{RED}143{RED_END}$"
.endif
Str_381E:
.if ENGLISH
  .string "{RED}144{RED_END}$"
.else
.string "{RED}144{RED_END}$"
.endif
Str_3824:
.if ENGLISH
  .string "{RED}145{RED_END}$"
.else
.string "{RED}145{RED_END}$"
.endif
Str_382A:
.if ENGLISH
  .string "{RED}146{RED_END}$"
.else
.string "{RED}146{RED_END}$"
.endif
Str_3830:
.if ENGLISH
  .string "{RED}147{RED_END}$"
.else
.string "{RED}147{RED_END}$"
.endif
Str_3836:
.if ENGLISH
  .string "{RED}148{RED_END}$"
.else
.string "{RED}148{RED_END}$"
.endif
Str_383C:
.if ENGLISH
  .string "{RED}149{RED_END}$"
.else
.string "{RED}149{RED_END}$"
.endif
Str_3842:
.if ENGLISH
  .string "{RED}150{RED_END}$"
.else
.string "{RED}150{RED_END}$"
.endif
Str_3848:
.if ENGLISH
  .string "{RED}151{RED_END}$"
.else
.string "{RED}151{RED_END}$"
.endif
Str_384E:
.if ENGLISH
  .string "{RED}152{RED_END}$"
.else
.string "{RED}152{RED_END}$"
.endif
Str_3854:
.if ENGLISH
  .string "{RED}153{RED_END}$"
.else
.string "{RED}153{RED_END}$"
.endif
Str_385A:
.if ENGLISH
  .string "{RED}154{RED_END}$"
.else
.string "{RED}154{RED_END}$"
.endif
Str_3860:
.if ENGLISH
  .string "{RED}155{RED_END}$"
.else
.string "{RED}155{RED_END}$"
.endif
Str_3866:
.if ENGLISH
  .string "{RED}156{RED_END}$"
.else
.string "{RED}156{RED_END}$"
.endif
Str_386C:
.if ENGLISH
  .string "{RED}157{RED_END}$"
.else
.string "{RED}157{RED_END}$"
.endif
Str_3872:
.if ENGLISH
  .string "{RED}158{RED_END}$"
.else
.string "{RED}158{RED_END}$"
.endif
Str_3878:
.if ENGLISH
  .string "{RED}159{RED_END}$"
.else
.string "{RED}159{RED_END}$"
.endif
Str_387E:
.if ENGLISH
  .string "{RED}160{RED_END}$"
.else
.string "{RED}160{RED_END}$"
.endif
Str_3884:
.if ENGLISH
  .string "{RED}161{RED_END}$"
.else
.string "{RED}161{RED_END}$"
.endif
Str_388A:
.if ENGLISH
  .string "{RED}162{RED_END}$"
.else
.string "{RED}162{RED_END}$"
.endif
Str_3890:
.if ENGLISH
  .string "{RED}163{RED_END}$"
.else
.string "{RED}163{RED_END}$"
.endif
Str_3896:
.if ENGLISH
  .string "{RED}164{RED_END}$"
.else
.string "{RED}164{RED_END}$"
.endif
Str_389C:
.if ENGLISH
  .string "{RED}165{RED_END}$"
.else
.string "{RED}165{RED_END}$"
.endif
Str_38A2:
.if ENGLISH
  .string "{RED}166{RED_END}$"
.else
.string "{RED}166{RED_END}$"
.endif
Str_38A8:
.if ENGLISH
  .string "{RED}167{RED_END}$"
.else
.string "{RED}167{RED_END}$"
.endif
Str_38AE:
.if ENGLISH
  .string "{RED}168{RED_END}$"
.else
.string "{RED}168{RED_END}$"
.endif
Str_38B4:
.if ENGLISH
  .string "{RED}169{RED_END}$"
.else
.string "{RED}169{RED_END}$"
.endif
Str_38BA:
.if ENGLISH
  .string "{RED}170{RED_END}$"
.else
.string "{RED}170{RED_END}$"
.endif
Str_38C0:
.if ENGLISH
  .string "{RED}171{RED_END}$"
.else
.string "{RED}171{RED_END}$"
.endif
Str_38C6:
.if ENGLISH
  .string "{RED}172{RED_END}$"
.else
.string "{RED}172{RED_END}$"
.endif
Str_38CC:
.if ENGLISH
  .string "{RED}173{RED_END}$"
.else
.string "{RED}173{RED_END}$"
.endif
Str_38D2:
.if ENGLISH
  .string "{RED}174{RED_END}$"
.else
.string "{RED}174{RED_END}$"
.endif
Str_38D8:
.if ENGLISH
  .string "{RED}175{RED_END}$"
.else
.string "{RED}175{RED_END}$"
.endif
Str_38DE:
.if ENGLISH
  .string "{RED}176{RED_END}$"
.else
.string "{RED}176{RED_END}$"
.endif
Str_38E4:
.if ENGLISH
  .string "{RED}177{RED_END}$"
.else
.string "{RED}177{RED_END}$"
.endif
Str_38EA:
.if ENGLISH
  .string "{RED}178{RED_END}$"
.else
.string "{RED}178{RED_END}$"
.endif
Str_38F0:
.if ENGLISH
  .string "{RED}179{RED_END}$"
.else
.string "{RED}179{RED_END}$"
.endif
Str_38F6:
.if ENGLISH
  .string "{RED}180{RED_END}$"
.else
.string "{RED}180{RED_END}$"
.endif
