Text_Disk_000:

Text_Disk_001::
	.string "オートチャージ\n"
	.string "{RED}(ヘッドチップ){RED_END}\n"
	.string "\n"
	.string "ボタンをおさなくても\n"
	.string "自動的にブキを\n"
	.string "チャージしてくれる$"

Text_Disk_002::
	.string "オートリカバリー\n"
	.string "{RED}(ヘッドチップ){RED_END}\n"
	.string "\n"
	.string "たち止まっていると\n"
	.string "自動的に体力を\n"
	.string "かいふくしてくれる$"

Text_Disk_003::
	.string "クイックチャージ\n"
	.string "{RED}(ヘッドチップ){RED_END}\n"
	.string "\n"
	.string "ブキのチャージ時間が\n"
	.string "はやくなる$"

Text_Disk_004::
	.string "フロッグ\n"
	.string "{RED}(フットチップ){RED_END}\n"
	.string "\n"
	.string "かべからずりおちる\n"
	.string "そくどがおそくなる$"

Text_Disk_005::
	.string "スプラッシュジャンプ\n"
	.string "{RED}(フットチップ){RED_END}\n"
	.string "\n"
	.string "すいめんを\n"
	.string "ジャンプできる$"

Text_Disk_006::
	.string "アルティメットフット\n"
	.string "{RED}(フットチップ){RED_END}\n"
	.string "\n"
	.string "すべてのフットチップの\n"
	.string "のうりょくが\n"
	.string "使えるようになる$"

Text_Disk_007::
	.string "{RED}ファイルA{RED_END}\n"
	.string "ミュートスレプリロイド\n"
	.string "とは、人間を守るために\n"
	.string "神ジュウなどをもとにして\n"
	.string "作られたレプリロイドの\n"
	.string "ことである$"

Text_Disk_008::
	.string "{RED}ファイルB{RED_END}\n"
	.string "ネオ・アルカディアとは、\n"
	.string "イレギュラーのいない\n"
	.string "平和な世界をめざして\n"
	.string "きずきあげられた\n"
	.string "ユートピアのことである$"

Text_Disk_009::
	.string "{RED}ファイルC{RED_END}\n"
	.string "サイバーエルフとは、\n"
	.string "人間やレプリロイドを\n"
	.string "助けるために作られた\n"
	.string "プログラムのいっしゅで、\n"
	.string "自分のイシをもっている$"

Text_Disk_010::
	.string "{RED}ファイルD{RED_END}\n"
	.string "ドクター・バイルとは、\n"
	.string "マザーエルフを改造し\n"
	.string "ヨウセイ戦争を\n"
	.string "ひきおこした科学者である$"

Text_Disk_011::
	.string "{RED}ファイルE{RED_END}\n"
	.string "パンテオンとは、\n"
	.string "エックスを機械的に\n"
	.string "れっかコピーした\n"
	.string "リョウサン型の\n"
	.string "レプリロイドである$"

Text_Disk_012::
	.string "{RED}ファイルF{RED_END}\n"
	.string "レジスタンスとは、\n"
	.string "イレギュラーとして\n"
	.string "ショブンされそうになった\n"
	.string "レプリロイドたちで\n"
	.string "作られたソシキである$"

Text_Disk_013::
	.string "{RED}ファイルG{RED_END}\n"
	.string "サイバーエルフXとは、\n"
	.string "オリジナルエックスの\n"
	.string "エルフのことであり、\n"
	.string "現在は ボディを\n"
	.string "うしなったままである$"

Text_Disk_014::
	.string "{RED}ファイルH{RED_END}\n"
	.string "四天王とは、\n"
	.string "エックスDNAの\n"
	.string "クローニングによって\n"
	.string "作り出された\n"
	.string "レプリロイドたちである$"

Text_Disk_015::
	.string "{RED}ファイルI{RED_END}\n"
	.string "エルピスとは、もともと\n"
	.string "ネオ・アルカディアにいた\n"
	.string "レプリロイドであり、\n"
	.string "ダークエルフの力によって\n"
	.string "あわれなマツロをたどる$"

Text_Disk_016::
	.string "{RED}ファイルJ{RED_END}\n"
	.string "ダークエルフとは、\n"
	.string "もともとイレギュラーを\n"
	.string "すくうために作られ、\n"
	.string "バイルにより悪用された\n"
	.string "マザーエルフである$"

Text_Disk_017::
	.string "{RED}ファイルK{RED_END}\n"
	.string "オメガとは、バイルに\n"
	.string "作られ、ヨウセイ戦争の\n"
	.string "ヒゲキをくりかえさぬよう\n"
	.string "ウチュウにツイホウされた\n"
	.string "レプリロイドである$"

Text_Disk_018::
	.string "{RED}ファイルL{RED_END}\n"
	.string "ヨウセイ戦争とは、\n"
	.string "イレギュラー戦争のまっき\n"
	.string "ダークエルフの使用により\n"
	.string "シジョウ最悪のケツマツを\n"
	.string "むかえた戦争である$"

Text_Disk_019::
	.string "{RED}ファイルM{RED_END}\n"
	.string "この世界のイレギュラーは\n"
	.string "ネオ・アルカディアに\n"
	.string "そむく者たちのことも\n"
	.string "ふくみ、本来のイミとは\n"
	.string "多少ちがっている$"

Text_Disk_020::
	.string "{RED}ファイルN{RED_END}\n"
	.string "Σ(シグマ)ウィルスとは\n"
	.string "レプリロイドの心を\n"
	.string "むしばみ、\n"
	.string "イレギュラー化させる\n"
	.string "ウィルスプログラムである$"

# size: 20 bytes
sDiskElf:: @ 0x083753f1
  .string "中にサイバーエルフ$"
  .string "が$"
  .string "入っていた$"

# size: 21 bytes
sDiskEC: @ 0x08375405
  .string "中にEクリスタル$"
  .string "ECが$"
  .string "入っていた$"

Text_Disk_111:: @ 0x0837541A
	.string "オメガ\n"
	.string "\n"
	.string "ダークエルフと同じ\n"
	.string "エネルギーはんのうを\n"
	.string "しめす なぞの\n"
	.string "巨大レプリロイド$"

Text_Disk_112:: @ 0x08375448
	.string "デスタンツ・マンティスク\n"
	.string "\n"
	.string "ショケイ用として\n"
	.string "カイハツされたため\n"
	.string "リョウテが巨大な\n"
	.string "カマになっている$"

Text_Disk_113:: @ 0x0837547E
	.string "チルドレ・イナラビッタ\n"
	.string "\n"
	.string "小型化することにより\n"
	.string "コウソク機動が\n"
	.string "カノウになっている$"

Text_Disk_114:: @ 0x083754AD
	.string "ブレイジン・フリザード\n"
	.string "\n"
	.string "しっぽとエリの\n"
	.string "きりはなしがカノウな\n"
	.string "エリマキトカゲ型\n"
	.string "レプリロイド$"

Text_Disk_115:: @ 0x083754DE
	.string "ヘルバット・シルト\n"
	.string "\n"
	.string "小型ていさつユニットの\n"
	.string "コウモリ型メカニロイドを\n"
	.string "マントの中から出して\n"
	.string "コウゲキしてくる$"

Text_Disk_116:: @ 0x0837551B
	.string "クリエ\n"
	.string "\n"
	.string "アルエットによって\n"
	.string "名づけられた\n"
	.string "青いベビーエルフ$"

Text_Disk_117:: @ 0x0837553C
	.string "プリエ\n"
	.string "\n"
	.string "アルエットによって\n"
	.string "名づけられた\n"
	.string "赤いベビーエルフ$"

Text_Disk_118:: @ 0x0837555D
	.string "アヌビステップ・\n"
	.string "  ネクロマンセス5世\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "ジャッカル型レプリロイド$"

Text_Disk_119:: @ 0x08375591
	.string "ハヌマシーンR\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "サル型レプリロイド$"

Text_Disk_120:: @ 0x083755B4
	.string "ブリザック・スタグロフR\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "ヘラジカ型レプリロイド$"

Text_Disk_121:: @ 0x083755DE
	.string "コピーエックスMK2\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "コピーエックスの\n"
	.string "カイリョウ型$"

Text_Disk_122:: @ 0x0837560A
	.string "トレテスタ・ケルベリアン\n"
	.string "\n"
	.string "リョウカタについた\n"
	.string "2つのあたまは\n"
	.string "きりはなすことができ\n"
	.string "どくりつした動きがカノウ$"

Text_Disk_123:: @ 0x08375643
	.string "グラチャー・\n"
	.string "   レ・カクタンク\n"
	.string "\n"
	.string "くさりでつながれたウデは\n"
	.string "ふりまわしたり、\n"
	.string "ぶらさがることがカノウ$"

Text_Disk_124:: @ 0x08375678
	.string "キュービット・\n"
	.string "    フォクスター\n"
	.string "\n"
	.string "9つのオプションを\n"
	.string "えんかくそうさしてくる\n"
	.string "キツネ型レプリロイド$"

Text_Disk_125:: @ 0x083756AE
	.string "ヴォルティール・\n"
	.string "    ビブリーオ\n"
	.string "\n"
	.string "すいちゅうせんようの\n"
	.string "ウナギ型レプリロイドで\n"
	.string "でんきコウゲキがトクイ$"

Text_Disk_126:: @ 0x083756E6
	.string "パンテオン・ハンター\n"
	.string "\n"
	.string "3れんしゃがカノウな\n"
	.string "じゅうをソウビしている$"

Text_Disk_127:: @ 0x08375709
	.string "パンテオン・ガーディアン\n"
	.string "\n"
	.string "デンゲキこうげきが\n"
	.string "カノウなけいぼうをもった\n"
	.string "パンテオン$"

Text_Disk_128:: @ 0x08375734
	.string "パンテオン・アクア\n"
	.string "\n"
	.string "うでからモリを\n"
	.string "ハッシャしてくる\n"
	.string "すいちゅうせんようの\n"
	.string "パンテオン$"

Text_Disk_129:: @ 0x08375761
	.string "パンテオン・フィスト\n"
	.string "\n"
	.string "テキが近づくと\n"
	.string "パンチでつっこんでくる$"

Text_Disk_130:: @ 0x08375782
	.string "パンテオン・ベース\n"
	.string "\n"
	.string "ホバーにのって\n"
	.string "ハンマーをふりまわす\n"
	.string "パンテオン$"

Text_Disk_131:: @ 0x083757A6
	.string "ダスロック\n"
	.string "\n"
	.string "工場のハイヒンを\n"
	.string "かためて作られた\n"
	.string "リサイクルメカニロイド\n"
	.string "$"

Text_Disk_132:: @ 0x083757CE
	.string "ジャイロキャノン\n"
	.string "\n"
	.string "プロペラで上下に\n"
	.string "ふゆうしている\n"
	.string "旧シキのメカニロイド$"

Text_Disk_133:: @ 0x083757F7
	.string "グランドキャノン\n"
	.string "\n"
	.string "ヒョウメンがコオリで\n"
	.string "コーティングされた\n"
	.string "カンレイ地センヨウの\n"
	.string "ホウダイ$"

Text_Disk_134:: @ 0x08375827
	.string "タイルキャノン\n"
	.string "\n"
	.string "かべのウラガワに\n"
	.string "かくれていて\n"
	.string "テイキ的にひっくりかえる$"

Text_Disk_135:: @ 0x0837584E
	.string "ピラーキャノン\n"
	.string "\n"
	.string "ハシラのまわりを\n"
	.string "回転イドウして\n"
	.string "コウゲキするホウダイ$"

Text_Disk_136:: @ 0x08375875
	.string "ヘビーキャノン\n"
	.string "\n"
	.string "ホウシンからとびだす\n"
	.string "タマのおもさは\n"
	.string "やく1トン$"

Text_Disk_137:: @ 0x08375897
	.string "カプセルキャノン\n"
	.string "\n"
	.string "シャッターが開くと\n"
	.string "2方向にわかれた\n"
	.string "タマをハッシャしてくる$"

Text_Disk_138:: @ 0x083758C3
	.string "ジェネレーターキャノン\n"
	.string "\n"
	.string "小型のメカニロイドを\n"
	.string "内部でセイサンする\n"
	.string "キノウがある$"

Text_Disk_139:: @ 0x083758F0
	.string "アイキャノン\n"
	.string "\n"
	.string "エリアをカンシし\n"
	.string "シンニュウ者を見つけると\n"
	.string "コウゲキしてくる$"

Text_Disk_140:: @ 0x08375919
	.string "シュリンポリン\n"
	.string "\n"
	.string "砂やユキの中を\n"
	.string "コウソクいどうできる\n"
	.string "エビのような形をした\n"
	.string "メカニロイド$"

Text_Disk_141:: @ 0x0837594A
	.string "ヴォルケール\n"
	.string "\n"
	.string "ヨウガンのネツを\n"
	.string "体内にとじこめ\n"
	.string "クウチュウで\n"
	.string "2つにブンレツする$"

Text_Disk_142:: @ 0x08375976
	.string "クラベッガー\n"
	.string "\n"
	.string "テンジョウにはりつき\n"
	.string "小さなヒカリの\n"
	.string "タマを上からおとす$"

Text_Disk_143:: @ 0x0837599D
	.string "ぺタトリア\n"
	.string "\n"
	.string "弱点である目を\n"
	.string "コウゲキしないと\n"
	.string "フッカツしてしまう$"

Text_Disk_144:: @ 0x083759C2
	.string "ショットロイド\n"
	.string "\n"
	.string "小きざみにあるいて\n"
	.string "タマをハッシャする\n"
	.string "メカニロイド$"

Text_Disk_145:: @ 0x083759E7
	.string "セーメラン\n"
	.string "\n"
	.string "バラとチューリップを\n"
	.string "たしたようなニオイのする\n"
	.string "しょくぶつ型メカニロイド$"

Text_Disk_146:: @ 0x08375A14
	.string "ランプロート\n"
	.string "\n"
	.string "もともとはサカナを\n"
	.string "やくための\n"
	.string "メカニロイド$"

Text_Disk_147:: @ 0x08375A33
	.string "レミングルス\n"
	.string "\n"
	.string "つねに4ひきで行動する\n"
	.string "とても仲のいい\n"
	.string "ネズミ型メカニロイド$"

Text_Disk_148:: @ 0x08375A5E
	.string "キャタタンク\n"
	.string "\n"
	.string "タテでガードし\n"
	.string "パンチでコウゲキしてくる$"

Text_Disk_149:: @ 0x08375A7B
	.string "トップガビョール\n"
	.string "\n"
	.string "ゆかやかべなどを\n"
	.string "オウフクいどうしている\n"
	.string "メカニロイド$"

Text_Disk_150:: @ 0x08375AA1
	.string "スネーケーブル\n"
	.string "\n"
	.string "ふだんはテンジョウに\n"
	.string "ぶらさがっており、\n"
	.string "きりはなされると\n"
	.string "かみついてくる$"

Text_Disk_151:: @ 0x08375AD0
	.string "ガリスニー\n"
	.string "\n"
	.string "ケイホウそうちに\n"
	.string "ひっかかると\n"
	.string "あらわれるメカニロイド$"

Text_Disk_152:: @ 0x08375AF3
	.string "クロスバイン\n"
	.string "\n"
	.string "ワープしながら\n"
	.string "4方向にタマを\n"
	.string "ハッシャしてくる$"

Text_Disk_153:: @ 0x08375B16
	.string "フロッパー\n"
	.string "\n"
	.string "バクフウでまわりの\n"
	.string "テキをまきこむヘイキ$"

Text_Disk_154:: @ 0x08375B32
	.string "パープルナープル\n"
	.string "\n"
	.string "下部がバクダンに\n"
	.string "なっている\n"
	.string "ひこう型メカニロイド$"

Text_Disk_155:: @ 0x08375B59
	.string "モスジーロ\n"
	.string "\n"
	.string "ヒカリに集まる\n"
	.string "シュウセイがある$"

Text_Disk_156:: @ 0x08375B72
	.string "バットンリング\n"
	.string "\n"
	.string "ハネをとじているときは\n"
	.string "どんなコウゲキも\n"
	.string "はねかえす$"

Text_Disk_157:: @ 0x08375B96
	.string "メルネット\n"
	.string "\n"
	.string "ハリを向けて、とんでくる\n"
	.string "ゴエイ用の\n"
	.string "ハチ型メカニロイド$"

Text_Disk_158:: @ 0x08375BBD
	.string "シャットカウンター\n"
	.string "\n"
	.string "前方からのコウゲキを\n"
	.string "ボウギョしている\n"
	.string "ひこう型メカニロイド$"

Text_Disk_159:: @ 0x08375BEA
	.string "シャークシールX\n"
	.string "\n"
	.string "サメ型メカニロイドの\n"
	.string "カイリョウばんで\n"
	.string "エモノにかみついてくる$"

Text_Disk_160:: @ 0x08375C15
	.string "シェルーノー\n"
	.string "\n"
	.string "ヒョウテキをサーチして\n"
	.string "おもに はいごから\n"
	.string "おそいかかってくる$"

Text_Disk_161:: @ 0x08375C3D
	.string "アイスボン\n"
	.string "\n"
	.string "カイテイでコオリを\n"
	.string "セイゾウしている$"

Text_Disk_162:: @ 0x08375C57
	.string "シェルクローラー\n"
	.string "\n"
	.string "ボウギョ用のカラを\n"
	.string "ハカイされると\n"
	.string "後方ににげていく$"

Text_Disk_163:: @ 0x08375C7F
	.string "キャノンホッパー\n"
	.string "\n"
	.string "てんじょうやゆかに\n"
	.string "はりついて\n"
	.string "タマをばらまいてくる$"

Text_Disk_164:: @ 0x08375CA4
	.string "バイル\n"
	.string "\n"
	.string "ネオ・アルカディアで\n"
	.string "レプリロイドを\n"
	.string "作っていた科学者$"

Text_Disk_165:: @ 0x08375CC9
	.string "シエル\n"
	.string "\n"
	.string "エネルギー開発を\n"
	.string "センモンとする\n"
	.string "科学者の少女$"

Text_Disk_166:: @ 0x08375CED
	.string "セルヴォ\n"
	.string "\n"
	.string "ゼロのために\n"
	.string "新しいブキを\n"
	.string "作ってくれるギジュツ者$"

Text_Disk_167:: @ 0x08375D10
	.string "アンドリュー\n"
	.string "\n"
	.string "むかし話を人に\n"
	.string "聞かせるのが大すきな\n"
	.string "ろうじん型のレプリロイド$"

Text_Disk_168:: @ 0x08375D3D
	.string "アルエット\n"
	.string "\n"
	.string "シエルに作ってもらった\n"
	.string "人形をいつもダイジに\n"
	.string "かかえている$"

Text_Disk_169:: @ 0x08375D65
	.string "イブー\n"
	.string "\n"
	.string "Eクリスタルが\n"
	.string "何よりも大すきな\n"
	.string "くいしんぼうレプリロイド$"

Text_Disk_170:: @ 0x08375D8A
	.string "ロシニョル\n"
	.string "\n"
	.string "メンテナンス・ルームで\n"
	.string "キズついたレジスタンスの\n"
	.string "手あてをしている$"

Text_Disk_171:: @ 0x08375DB4
	.string "ぺロケ\n"
	.string "\n"
	.string "ずのうメイセキで\n"
	.string "シエルの助手を\n"
	.string "つとめている$"

Text_Disk_172:: @ 0x08375DD3
	.string "オトリッシュ\n"
	.string "\n"
	.string "シンチョウが高く\n"
	.string "キョダツ感のある会話が\n"
	.string "とくちょう的な\n"
	.string "レプリロイド$"

Text_Disk_173:: @ 0x08375E04
	.string "イロンデル\n"
	.string "\n"
	.string "世界中をとびまわり、\n"
	.string "ありとあらゆる\n"
	.string "ジョウホウを集めている$"

Text_Disk_174:: @ 0x08375E2E
	.string "ドワ\n"
	.string "\n"
	.string "セルヴォの助手をつとめ\n"
	.string "レジスタンスのブキを\n"
	.string "作っている$"

Text_Disk_175:: @ 0x08375E52
	.string "メナート\n"
	.string "\n"
	.string "しごとをするのがきらいで\n"
	.string "いつもサボってばかりいる\n"
	.string "いたずらっこ$"

Text_Disk_176:: @ 0x08375E79
	.string "ピック\n"
	.string "\n"
	.string "口を開けば\n"
	.string "イヤミなことばかり言う\n"
	.string "少しひねくれた\n"
	.string "レプリロイド$"

Text_Disk_177:: @ 0x08375EA3
	.string "ハルピュイア\n"
	.string "\n"
	.string "賢将のイミョウをもつ\n"
	.string "緑の四天王。\n"
	.string "レックウ軍団を\n"
	.string "ひきいる$"

Text_Disk_178:: @ 0x08375ED2
	.string "ファーブニル\n"
	.string "\n"
	.string "闘将のイミョウをもつ\n"
	.string "赤き四天王。\n"
	.string "ジンエン軍団を\n"
	.string "ひきいる$"

Text_Disk_179:: @ 0x08375F01
	.string "レヴィアタン\n"
	.string "\n"
	.string "妖将のイミョウをもつ\n"
	.string "青き四天王。\n"
	.string "メイカイ軍団を\n"
	.string "ひきいる$"

Text_Disk_180:: @ 0x08375F30
	.string "ファントム\n"
	.string "\n"
	.string "隠将のイミョウをもつ\n"
	.string "ヤミの四天王。\n"
	.string "ザンエイ軍団を\n"
	.string "ひきいる$"
