Text_Disk_000:

Text_Disk_001::
Str_24A0:
.if ENGLISH
	.string "AUTO-CHARGE\n"
	.string "{RED}(Head Chip){RED_END}\n"
	.string "\n"
	.string "Automatic\n"
	.string "charge to\n"
	.string "your weapon.$"
.else
	.string "オートチャージ\n"
	.string "{RED}(ヘッドチップ){RED_END}\n"
	.string "\n"
	.string "ボタンをおさなくても\n"
	.string "自動的にブキを\n"
	.string "チャージしてくれる$"
.endif

Text_Disk_002::
Str_24D4:
.if ENGLISH
	.string "AUTO-RECOVER\n"
	.string "{RED}(Head Chip){RED_END}\n"
	.string "\n"
	.string "Automatic\n"
	.string "recovery of\n"
	.string "vitality.$"
.else
	.string "オートリカバリー\n"
	.string "{RED}(ヘッドチップ){RED_END}\n"
	.string "\n"
	.string "たち止まっていると\n"
	.string "自動的に体力を\n"
	.string "かいふくしてくれる$"
.endif

Text_Disk_003::
Str_250B:
.if ENGLISH
	.string "QUICK-CHARGE\n"
	.string "{RED}(Head Chip){RED_END}\n"
	.string "\n"
	.string "Boosts your\n"
	.string "charge spd.$"
.else
	.string "クイックチャージ\n"
	.string "{RED}(ヘッドチップ){RED_END}\n"
	.string "\n"
	.string "ブキのチャージ時間が\n"
	.string "はやくなる$"
.endif

Text_Disk_004::
Str_2533:
.if ENGLISH
	.string "FROG\n"
	.string "{RED}(Foot Chip){RED_END}\n"
	.string "\n"
	.string "Slide slower\n"
	.string "down walls.$"
.else
	.string "フロッグ\n"
	.string "{RED}(フットチップ){RED_END}\n"
	.string "\n"
	.string "かべからずりおちる\n"
	.string "そくどがおそくなる$"
.endif

Text_Disk_005::
Str_2558:
.if ENGLISH
	.string "SPLASH JUMP\n"
	.string "{RED}(Foot Chip){RED_END}\n"
	.string "\n"
	.string "Jump on\n"
	.string "water.$"
.else
	.string "スプラッシュジャンプ\n"
	.string "{RED}(フットチップ){RED_END}\n"
	.string "\n"
	.string "すいめんを\n"
	.string "ジャンプできる$"
.endif

Text_Disk_006::
Str_257D:
.if ENGLISH
	.string "ULTIMA FOOT\n"
	.string "{RED}(Foot Chip){RED_END}\n"
	.string "\n"
	.string "Can use all\n"
	.string "Foot Chip\n"
	.string "traits.$"
.else
	.string "アルティメットフット\n"
	.string "{RED}(フットチップ){RED_END}\n"
	.string "\n"
	.string "すべてのフットチップの\n"
	.string "のうりょくが\n"
	.string "使えるようになる$"
.endif

Text_Disk_007::
Str_25B1:
.if ENGLISH
	.string "{RED}FILE A{RED_END}\n"
	.string "The beast-\n"
	.string "like Mutos\n"
	.string "Reploids\n"
	.string "defend the \n"
	.string "human race.$"
.else
	.string "{RED}ファイルA{RED_END}\n"
	.string "ミュートスレプリロイド\n"
	.string "とは、人間を守るために\n"
	.string "神ジュウなどをもとにして\n"
	.string "作られたレプリロイドの\n"
	.string "ことである$"
.endif

Text_Disk_008::
Str_25F5:
.if ENGLISH
	.string "{RED}FILE B{RED_END}\n"
	.string "Neo Arcadia\n"
	.string "is a utopia\n"
	.string "of peace\n"
	.string "without any\n"
	.string "Mavericks.$"
.else
	.string "{RED}ファイルB{RED_END}\n"
	.string "ネオ・アルカディアとは、\n"
	.string "イレギュラーのいない\n"
	.string "平和な世界をめざして\n"
	.string "きずきあげられた\n"
	.string "ユートピアのことである$"
.endif

Text_Disk_009::
Str_2639:
.if ENGLISH
	.string "{RED}FILE C{RED_END}\n"
	.string "Cyber-elves\n"
	.string "are smart\n"
	.string "programs for\n"
	.string "helping man\n"
	.string "and Reploid.$"
.else
	.string "{RED}ファイルC{RED_END}\n"
	.string "サイバーエルフとは、\n"
	.string "人間やレプリロイドを\n"
	.string "助けるために作られた\n"
	.string "プログラムのいっしゅで、\n"
	.string "自分のイシをもっている$"
.endif

Text_Disk_010::
Str_2681:
.if ENGLISH
	.string "{RED}FILE D{RED_END}\n"
	.string "Weil altered\n"
	.string "Mother Elf,\n"
	.string "starting the\n"
	.string "Elf Wars.$"
.else
	.string "{RED}ファイルD{RED_END}\n"
	.string "ドクター・バイルとは、\n"
	.string "マザーエルフを改造し\n"
	.string "ヨウセイ戦争を\n"
	.string "ひきおこした科学者である$"
.endif

Text_Disk_011::
Str_26BC:
.if ENGLISH
	.string "{RED}FILE E{RED_END}\n"
	.string "Pantheon are\n"
	.string "degraded,\n"
	.string "massproduced\n"
	.string "Reploid\n"
	.string "copies of X.$"
.else
	.string "{RED}ファイルE{RED_END}\n"
	.string "パンテオンとは、\n"
	.string "エックスを機械的に\n"
	.string "れっかコピーした\n"
	.string "リョウサン型の\n"
	.string "レプリロイドである$"
.endif

Text_Disk_012::
Str_26F6:
.if ENGLISH
	.string "{RED}FILE F{RED_END}\n"
	.string "Maverick\n"
	.string "Reploids\n"
	.string "fated to die\n"
	.string "formed the\n"
	.string "Resistance.$"
.else
	.string "{RED}ファイルF{RED_END}\n"
	.string "レジスタンスとは、\n"
	.string "イレギュラーとして\n"
	.string "ショブンされそうになった\n"
	.string "レプリロイドたちで\n"
	.string "作られたソシキである$"
.endif

Text_Disk_013::
Str_2735:
.if ENGLISH
	.string "{RED}FILE G{RED_END}\n"
	.string "Cyber-elf X\n"
	.string "was once the\n"
	.string "original X,\n"
	.string "but now he\n"
	.string "has no body.$"
.else
	.string "{RED}ファイルG{RED_END}\n"
	.string "サイバーエルフXとは、\n"
	.string "オリジナルエックスの\n"
	.string "エルフのことであり、\n"
	.string "現在は ボディを\n"
	.string "うしなったままである$"
.endif

Text_Disk_014::
Str_2775:
.if ENGLISH
	.string "{RED}FILE H{RED_END}\n"
	.string "The Four\n"
	.string "Guardians\n"
	.string "are Reploids\n"
	.string "made from\n"
	.string "DNA of X.$"
.else
	.string "{RED}ファイルH{RED_END}\n"
	.string "四天王とは、\n"
	.string "エックスDNAの\n"
	.string "クローニングによって\n"
	.string "作り出された\n"
	.string "レプリロイドたちである$"
.endif

Text_Disk_015::
Str_27B0:
.if ENGLISH
	.string "{RED}FILE I{RED_END}\n"
	.string "Elpizo was a\n"
	.string "Neo Arcadian\n"
	.string "Reploid that\n"
	.string "was seduced\n"
	.string "by Dark Elf.$"
.else
	.string "{RED}ファイルI{RED_END}\n"
	.string "エルピスとは、もともと\n"
	.string "ネオ・アルカディアにいた\n"
	.string "レプリロイドであり、\n"
	.string "ダークエルフの力によって\n"
	.string "あわれなマツロをたどる$"
.endif

Text_Disk_016::
Str_27F6:
.if ENGLISH
	.string "{RED}FILE J{RED_END}\n"
	.string "Dark Elf was\n"
	.string "Mother Elf\n"
	.string "before Dr.\n"
	.string "Weil altered\n"
	.string "her.$"
.else
	.string "{RED}ファイルJ{RED_END}\n"
	.string "ダークエルフとは、\n"
	.string "もともとイレギュラーを\n"
	.string "すくうために作られ、\n"
	.string "バイルにより悪用された\n"
	.string "マザーエルフである$"
.endif

Text_Disk_017::
Str_2838:
.if ENGLISH
	.string "{RED}FILE K{RED_END}\n"
	.string "Omega was\n"
	.string "made by Dr.\n"
	.string "Weil, but \n"
	.string "was banished\n"
	.string "to space.$"
.else
	.string "{RED}ファイルK{RED_END}\n"
	.string "オメガとは、バイルに\n"
	.string "作られ、ヨウセイ戦争の\n"
	.string "ヒゲキをくりかえさぬよう\n"
	.string "ウチュウにツイホウされた\n"
	.string "レプリロイドである$"
.endif

Text_Disk_018::
Str_287E:
.if ENGLISH
	.string "{RED}FILE L{RED_END}\n"
	.string "Use of Dark\n"
	.string "Elf made the\n"
	.string "Elf Wars\n"
	.string "terribly\n"
	.string "tragic.$"
.else
	.string "{RED}ファイルL{RED_END}\n"
	.string "ヨウセイ戦争とは、\n"
	.string "イレギュラー戦争のまっき\n"
	.string "ダークエルフの使用により\n"
	.string "シジョウ最悪のケツマツを\n"
	.string "むかえた戦争である$"
.endif

Text_Disk_019::
Str_28CB:
.if ENGLISH
	.string "{RED}FILE M{RED_END}\n"
	.string "A Maverick\n"
	.string "now means\n"
	.string "somebody who\n"
	.string "fights Neo\n"
	.string "Arcadia.$"
.else
	.string "{RED}ファイルM{RED_END}\n"
	.string "この世界のイレギュラーは\n"
	.string "ネオ・アルカディアに\n"
	.string "そむく者たちのことも\n"
	.string "ふくみ、本来のイミとは\n"
	.string "多少ちがっている$"
.endif

Text_Disk_020::
Str_2912:
.if ENGLISH
	.string "{RED}FILE N{RED_END}\n"
	.string "The Sigma\n"
	.string "virus turned\n"
	.string "Reploids\n"
	.string "into \n"
	.string "Mavericks.$"
.else
	.string "{RED}ファイルN{RED_END}\n"
	.string "Σ(シグマ)ウィルスとは\n"
	.string "レプリロイドの心を\n"
	.string "むしばみ、\n"
	.string "イレギュラー化させる\n"
	.string "ウィルスプログラムである$"
.endif

# size: 20 bytes
sDiskElf:: @ 0x083753f1
Str_2951:
.if ENGLISH
  .string "A Cyber-elf$"
.else
  .string "中にサイバーエルフ$"
.endif
Str_295C:
.if ENGLISH
  .string "$"
.else
  .string "が$"
.endif
Str_295E:
.if ENGLISH
  .string "was inside.$"
.else
  .string "入っていた$"
.endif

# size: 21 bytes
sDiskEC: @ 0x08375405
Str_2965:
.if ENGLISH
  .string "$"
.else
  .string "中にEクリスタル$"
.endif
Str_296F:
.if ENGLISH
  .string "E-Crystals$"
.else
  .string "ECが$"
.endif
Str_2973:
.if ENGLISH
  .string "were inside.$"
.else
  .string "入っていた$"
.endif

Text_Disk_111:: @ 0x0837541A
Str_297A:
.if ENGLISH
	.string "Omega\n"
	.string "\n"
	.string "This Reploid\n"
	.string "has a the\n"
	.string "signature\n"
	.string "of Dark Elf.$"
.else
	.string "オメガ\n"
	.string "\n"
	.string "ダークエルフと同じ\n"
	.string "エネルギーはんのうを\n"
	.string "しめす なぞの\n"
	.string "巨大レプリロイド$"
.endif

Text_Disk_112:: @ 0x08375448
Str_29A8:
.if ENGLISH
	.string "D. Mantisk\n"
	.string "\n"
	.string "Uses scythes\n"
	.string "to dispose\n"
	.string "of old\n"
	.string "Reploids.$"
.else
	.string "デスタンツ・マンティスク\n"
	.string "\n"
	.string "ショケイ用として\n"
	.string "カイハツされたため\n"
	.string "リョウテが巨大な\n"
	.string "カマになっている$"
.endif

Text_Disk_113:: @ 0x0837547E
Str_29DE:
.if ENGLISH
	.string "C. Inarbitta\n"
	.string "\n"
	.string "Can become\n"
	.string "small to \n"
	.string "boost speed.$"
.else
	.string "チルドレ・イナラビッタ\n"
	.string "\n"
	.string "小型化することにより\n"
	.string "コウソク機動が\n"
	.string "カノウになっている$"
.endif

Text_Disk_114:: @ 0x083754AD
Str_2A0D:
.if ENGLISH
	.string "B. Flizard\n"
	.string "\n"
	.string "This lizard\n"
	.string "can detach\n"
	.string "his tail and\n"
	.string "frill.$"
.else
	.string "ブレイジン・フリザード\n"
	.string "\n"
	.string "しっぽとエリの\n"
	.string "きりはなしがカノウな\n"
	.string "エリマキトカゲ型\n"
	.string "レプリロイド$"
.endif

Text_Disk_115:: @ 0x083754DE
Str_2A3E:
.if ENGLISH
	.string "D. Schilt\n"
	.string "\n"
	.string "Attacks with\n"
	.string "small bat\n"
	.string "drones from\n"
	.string "his cape.$"
.else
	.string "ヘルバット・シルト\n"
	.string "\n"
	.string "小型ていさつユニットの\n"
	.string "コウモリ型メカニロイドを\n"
	.string "マントの中から出して\n"
	.string "コウゲキしてくる$"
.endif

Text_Disk_116:: @ 0x0837551B
Str_2A7B:
.if ENGLISH
	.string "Crea\n"
	.string "\n"
	.string "A blue Baby\n"
	.string "Elf named by\n"
	.string "Alouette.$"
.else
	.string "クリエ\n"
	.string "\n"
	.string "アルエットによって\n"
	.string "名づけられた\n"
	.string "青いベビーエルフ$"
.endif

Text_Disk_117:: @ 0x0837553C
Str_2A9C:
.if ENGLISH
	.string "Prea\n"
	.string "\n"
	.string "A red Baby\n"
	.string "Elf named by\n"
	.string "Alouette.$"
.else
	.string "プリエ\n"
	.string "\n"
	.string "アルエットによって\n"
	.string "名づけられた\n"
	.string "赤いベビーエルフ$"
.endif

Text_Disk_118:: @ 0x0837555D
Str_2ABD:
.if ENGLISH
	.string "Anubis\n"
	.string "Necromncss V\n"
	.string "\n"
	.string "Jackal 'loid\n"
	.string "revived by\n"
	.string "Dr. Weil.$"
.else
	.string "アヌビステップ・\n"
	.string "  ネクロマンセス5世\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "ジャッカル型レプリロイド$"
.endif

Text_Disk_119:: @ 0x08375591
Str_2AF1:
.if ENGLISH
	.string "Hanumachne R\n"
	.string "\n"
	.string "Monkey 'loid\n"
	.string "revived by\n"
	.string "Dr. Weil.$"
.else
	.string "ハヌマシーンR\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "サル型レプリロイド$"
.endif

Text_Disk_120:: @ 0x083755B4
Str_2B14:
.if ENGLISH
	.string "B. Stagrff R\n"
	.string "\n"
	.string "Elk Reploid\n"
	.string "revived by\n"
	.string "Dr. Weil.$"
.else
	.string "ブリザック・スタグロフR\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "ヘラジカ型レプリロイド$"
.endif

Text_Disk_121:: @ 0x083755DE
Str_2B3E:
.if ENGLISH
	.string "Copy X MK.II\n"
	.string "\n"
	.string "A revised\n"
	.string "Copy X\n"
	.string "revived by\n"
	.string "Dr. Weil.$"
.else
	.string "コピーエックスMK2\n"
	.string "\n"
	.string "バイルによって\n"
	.string "フッカツした\n"
	.string "コピーエックスの\n"
	.string "カイリョウ型$"
.endif

Text_Disk_122:: @ 0x0837560A
Str_2B6A:
.if ENGLISH
	.string "T. Kelverian\n"
	.string "\n"
	.string "Can detach\n"
	.string "the 2 heads\n"
	.string "on his\n"
	.string "shoulders.$"
.else
	.string "トレテスタ・ケルベリアン\n"
	.string "\n"
	.string "リョウカタについた\n"
	.string "2つのあたまは\n"
	.string "きりはなすことができ\n"
	.string "どくりつした動きがカノウ$"
.endif

Text_Disk_123:: @ 0x08375643
Str_2BA3:
.if ENGLISH
	.string "Glacier\n"
	.string "Le Cactank\n"
	.string "\n"
	.string "Swings\n"
	.string "chained\n"
	.string "arms around.$"
.else
	.string "グラチャー・\n"
	.string "   レ・カクタンク\n"
	.string "\n"
	.string "くさりでつながれたウデは\n"
	.string "ふりまわしたり、\n"
	.string "ぶらさがることがカノウ$"
.endif

Text_Disk_124:: @ 0x08375678
Str_2BD8:
.if ENGLISH
	.string "Cubit\n"
	.string "Foxtar\n"
	.string "\n"
	.string "Fox Reploid\n"
	.string "that uses 9\n"
	.string "remotes.$"
.else
	.string "キュービット・\n"
	.string "    フォクスター\n"
	.string "\n"
	.string "9つのオプションを\n"
	.string "えんかくそうさしてくる\n"
	.string "キツネ型レプリロイド$"
.endif

Text_Disk_125:: @ 0x083756AE
Str_2C0E:
.if ENGLISH
	.string "Volteel\n"
	.string "Biblio\n"
	.string "\n"
	.string "Eel Reploid\n"
	.string "that uses\n"
	.string "electricity.$"
.else
	.string "ヴォルティール・\n"
	.string "    ビブリーオ\n"
	.string "\n"
	.string "すいちゅうせんようの\n"
	.string "ウナギ型レプリロイドで\n"
	.string "でんきコウゲキがトクイ$"
.endif

Text_Disk_126:: @ 0x083756E6
Str_2C46:
.if ENGLISH
	.string "P. Hunter\n"
	.string "\n"
	.string "Carries a\n"
	.string "3 shot gun.$"
.else
	.string "パンテオン・ハンター\n"
	.string "\n"
	.string "3れんしゃがカノウな\n"
	.string "じゅうをソウビしている$"
.endif

Text_Disk_127:: @ 0x08375709
Str_2C69:
.if ENGLISH
	.string "P. Guardian\n"
	.string "\n"
	.string "Carries an\n"
	.string "electric\n"
	.string "club.$"
.else
	.string "パンテオン・ガーディアン\n"
	.string "\n"
	.string "デンゲキこうげきが\n"
	.string "カノウなけいぼうをもった\n"
	.string "パンテオン$"
.endif

Text_Disk_128:: @ 0x08375734
Str_2C94:
.if ENGLISH
	.string "P. Aqua\n"
	.string "\n"
	.string "Shoots a\n"
	.string "harpoon\n"
	.string "from its\n"
	.string "arm.$"
.else
	.string "パンテオン・アクア\n"
	.string "\n"
	.string "うでからモリを\n"
	.string "ハッシャしてくる\n"
	.string "すいちゅうせんようの\n"
	.string "パンテオン$"
.endif

Text_Disk_129:: @ 0x08375761
Str_2CC1:
.if ENGLISH
	.string "P. Fist\n"
	.string "\n"
	.string "Punches\n"
	.string "when close.$"
.else
	.string "パンテオン・フィスト\n"
	.string "\n"
	.string "テキが近づくと\n"
	.string "パンチでつっこんでくる$"
.endif

Text_Disk_130:: @ 0x08375782
Str_2CE2:
.if ENGLISH
	.string "P. Base\n"
	.string "\n"
	.string "Rides a\n"
	.string "hovercraft,\n"
	.string "uses hammer.$"
.else
	.string "パンテオン・ベース\n"
	.string "\n"
	.string "ホバーにのって\n"
	.string "ハンマーをふりまわす\n"
	.string "パンテオン$"
.endif

Text_Disk_131:: @ 0x083757A6
Str_2D06:
.if ENGLISH
	.string "Deathlock\n"
	.string "\n"
	.string "Mechaniloid\n"
	.string "made from\n"
	.string "old parts.\n"
	.string "$"
.else
	.string "ダスロック\n"
	.string "\n"
	.string "工場のハイヒンを\n"
	.string "かためて作られた\n"
	.string "リサイクルメカニロイド\n"
	.string "$"
.endif

Text_Disk_132:: @ 0x083757CE
Str_2D2E:
.if ENGLISH
	.string "Gyro Cannon\n"
	.string "\n"
	.string "Floats up\n"
	.string "with a\n"
	.string "propeller.$"
.else
	.string "ジャイロキャノン\n"
	.string "\n"
	.string "プロペラで上下に\n"
	.string "ふゆうしている\n"
	.string "旧シキのメカニロイド$"
.endif

Text_Disk_133:: @ 0x083757F7
Str_2D57:
.if ENGLISH
	.string "Grand Cannon\n"
	.string "\n"
	.string "A cannon\n"
	.string "made for\n"
	.string "frozen\n"
	.string "terrain.$"
.else
	.string "グランドキャノン\n"
	.string "\n"
	.string "ヒョウメンがコオリで\n"
	.string "コーティングされた\n"
	.string "カンレイ地センヨウの\n"
	.string "ホウダイ$"
.endif

Text_Disk_134:: @ 0x08375827
Str_2D87:
.if ENGLISH
	.string "Tile Cannon\n"
	.string "\n"
	.string "A cannon\n"
	.string "that hides\n"
	.string "in walls.$"
.else
	.string "タイルキャノン\n"
	.string "\n"
	.string "かべのウラガワに\n"
	.string "かくれていて\n"
	.string "テイキ的にひっくりかえる$"
.endif

Text_Disk_135:: @ 0x0837584E
Str_2DAE:
.if ENGLISH
	.string "P. Cannon\n"
	.string "\n"
	.string "A cannon\n"
	.string "that attacks\n"
	.string "from poles.$"
.else
	.string "ピラーキャノン\n"
	.string "\n"
	.string "ハシラのまわりを\n"
	.string "回転イドウして\n"
	.string "コウゲキするホウダイ$"
.endif

Text_Disk_136:: @ 0x08375875
Str_2DD5:
.if ENGLISH
	.string "Heavy Cannon\n"
	.string "\n"
	.string "Shoots a\n"
	.string "one-ton\n"
	.string "cannonball.$"
.else
	.string "ヘビーキャノン\n"
	.string "\n"
	.string "ホウシンからとびだす\n"
	.string "タマのおもさは\n"
	.string "やく1トン$"
.endif

Text_Disk_137:: @ 0x08375897
Str_2DF7:
.if ENGLISH
	.string "C. Cannon\n"
	.string "\n"
	.string "Shoots 2\n"
	.string "shots from\n"
	.string "a capsule.$"
.else
	.string "カプセルキャノン\n"
	.string "\n"
	.string "シャッターが開くと\n"
	.string "2方向にわかれた\n"
	.string "タマをハッシャしてくる$"
.endif

Text_Disk_138:: @ 0x083758C3
Str_2E23:
.if ENGLISH
	.string "G. Cannon\n"
	.string "\n"
	.string "Creates\n"
	.string "small Mech-\n"
	.string "aniloids.$"
.else
	.string "ジェネレーターキャノン\n"
	.string "\n"
	.string "小型のメカニロイドを\n"
	.string "内部でセイサンする\n"
	.string "キノウがある$"
.endif

Text_Disk_139:: @ 0x083758F0
Str_2E50:
.if ENGLISH
	.string "Eye Cannon\n"
	.string "\n"
	.string "Spots\n"
	.string "intruders\n"
	.string "and attacks.$"
.else
	.string "アイキャノン\n"
	.string "\n"
	.string "エリアをカンシし\n"
	.string "シンニュウ者を見つけると\n"
	.string "コウゲキしてくる$"
.endif

Text_Disk_140:: @ 0x08375919
Str_2E79:
.if ENGLISH
	.string "Shrimpolin\n"
	.string "\n"
	.string "This foe can\n"
	.string "move quickly\n"
	.string "in sand or \n"
	.string "snow.$"
.else
	.string "シュリンポリン\n"
	.string "\n"
	.string "砂やユキの中を\n"
	.string "コウソクいどうできる\n"
	.string "エビのような形をした\n"
	.string "メカニロイド$"
.endif

Text_Disk_141:: @ 0x0837594A
Str_2EAA:
.if ENGLISH
	.string "Volcaire\n"
	.string "\n"
	.string "Stores lava\n"
	.string "inside body\n"
	.string "then splits\n"
	.string "mid-air.$"
.else
	.string "ヴォルケール\n"
	.string "\n"
	.string "ヨウガンのネツを\n"
	.string "体内にとじこめ\n"
	.string "クウチュウで\n"
	.string "2つにブンレツする$"
.endif

Text_Disk_142:: @ 0x08375976
Str_2ED6:
.if ENGLISH
	.string "Claveker\n"
	.string "\n"
	.string "This foe\n"
	.string "shoots from\n"
	.string "ceilings.$"
.else
	.string "クラベッガー\n"
	.string "\n"
	.string "テンジョウにはりつき\n"
	.string "小さなヒカリの\n"
	.string "タマを上からおとす$"
.endif

Text_Disk_143:: @ 0x0837599D
Str_2EFD:
.if ENGLISH
	.string "Petatria\n"
	.string "\n"
	.string "Revives if\n"
	.string "eye is not\n"
	.string "attacked.$"
.else
	.string "ぺタトリア\n"
	.string "\n"
	.string "弱点である目を\n"
	.string "コウゲキしないと\n"
	.string "フッカツしてしまう$"
.endif

Text_Disk_144:: @ 0x083759C2
Str_2F22:
.if ENGLISH
	.string "Shotloid\n"
	.string "\n"
	.string "Shoots while\n"
	.string "moving in\n"
	.string "small steps.$"
.else
	.string "ショットロイド\n"
	.string "\n"
	.string "小きざみにあるいて\n"
	.string "タマをハッシャする\n"
	.string "メカニロイド$"
.endif

Text_Disk_145:: @ 0x083759E7
Str_2F47:
.if ENGLISH
	.string "Seimeran\n"
	.string "\n"
	.string "This plant\n"
	.string "Mechaniloid\n"
	.string "smells nice.$"
.else
	.string "セーメラン\n"
	.string "\n"
	.string "バラとチューリップを\n"
	.string "たしたようなニオイのする\n"
	.string "しょくぶつ型メカニロイド$"
.endif

Text_Disk_146:: @ 0x08375A14
Str_2F74:
.if ENGLISH
	.string "Lamplort\n"
	.string "\n"
	.string "Mechaniloid\n"
	.string "made to cook\n"
	.string "fish.$"
.else
	.string "ランプロート\n"
	.string "\n"
	.string "もともとはサカナを\n"
	.string "やくための\n"
	.string "メカニロイド$"
.endif

Text_Disk_147:: @ 0x08375A33
Str_2F93:
.if ENGLISH
	.string "Lemmingles\n"
	.string "\n"
	.string "4 mouse-like\n"
	.string "Mechaniloids\n"
	.string "in a group.$"
.else
	.string "レミングルス\n"
	.string "\n"
	.string "つねに4ひきで行動する\n"
	.string "とても仲のいい\n"
	.string "ネズミ型メカニロイド$"
.endif

Text_Disk_148:: @ 0x08375A5E
Str_2FBE:
.if ENGLISH
	.string "Cattatank\n"
	.string "\n"
	.string "Guards with\n"
	.string "shield then\n"
	.string "punches.$"
.else
	.string "キャタタンク\n"
	.string "\n"
	.string "タテでガードし\n"
	.string "パンチでコウゲキしてくる$"
.endif

Text_Disk_149:: @ 0x08375A7B
Str_2FDB:
.if ENGLISH
	.string "Top Gabyoall\n"
	.string "\n"
	.string "Patrols\n"
	.string "floors and\n"
	.string "walls.$"
.else
	.string "トップガビョール\n"
	.string "\n"
	.string "ゆかやかべなどを\n"
	.string "オウフクいどうしている\n"
	.string "メカニロイド$"
.endif

Text_Disk_150:: @ 0x08375AA1
Str_3001:
.if ENGLISH
	.string "Snakecord\n"
	.string "\n"
	.string "Hangs from\n"
	.string "ceilings and\n"
	.string "bites when\n"
	.string "separated.$"
.else
	.string "スネーケーブル\n"
	.string "\n"
	.string "ふだんはテンジョウに\n"
	.string "ぶらさがっており、\n"
	.string "きりはなされると\n"
	.string "かみついてくる$"
.endif

Text_Disk_151:: @ 0x08375AD0
Str_3030:
.if ENGLISH
	.string "Gallisni\n"
	.string "\n"
	.string "Appears\n"
	.string "when alarm\n"
	.string "is tripped.$"
.else
	.string "ガリスニー\n"
	.string "\n"
	.string "ケイホウそうちに\n"
	.string "ひっかかると\n"
	.string "あらわれるメカニロイド$"
.endif

Text_Disk_152:: @ 0x08375AF3
Str_3053:
.if ENGLISH
	.string "Crossbyne\n"
	.string "\n"
	.string "Shoots 4-way\n"
	.string "bullets and\n"
	.string "warps.$"
.else
	.string "クロスバイン\n"
	.string "\n"
	.string "ワープしながら\n"
	.string "4方向にタマを\n"
	.string "ハッシャしてくる$"
.endif

Text_Disk_153:: @ 0x08375B16
Str_3076:
.if ENGLISH
	.string "Flopper\n"
	.string "\n"
	.string "Explodes,\n"
	.string "damaging\n"
	.string "close units.$"
.else
	.string "フロッパー\n"
	.string "\n"
	.string "バクフウでまわりの\n"
	.string "テキをまきこむヘイキ$"
.endif

Text_Disk_154:: @ 0x08375B32
Str_3092:
.if ENGLISH
	.string "PurpleNerple\n"
	.string "\n"
	.string "This foe\n"
	.string "has a bomb\n"
	.string "underneath.$"
.else
	.string "パープルナープル\n"
	.string "\n"
	.string "下部がバクダンに\n"
	.string "なっている\n"
	.string "ひこう型メカニロイド$"
.endif

Text_Disk_155:: @ 0x08375B59
Str_30B9:
.if ENGLISH
	.string "Mothjiro\n"
	.string "\n"
	.string "Congregates\n"
	.string "near light.$"
.else
	.string "モスジーロ\n"
	.string "\n"
	.string "ヒカリに集まる\n"
	.string "シュウセイがある$"
.endif

Text_Disk_156:: @ 0x08375B72
Str_30D2:
.if ENGLISH
	.string "Batring\n"
	.string "\n"
	.string "Repels any\n"
	.string "attack when\n"
	.string "wings close.$"
.else
	.string "バットンリング\n"
	.string "\n"
	.string "ハネをとじているときは\n"
	.string "どんなコウゲキも\n"
	.string "はねかえす$"
.endif

Text_Disk_157:: @ 0x08375B96
Str_30F6:
.if ENGLISH
	.string "Mellnet\n"
	.string "\n"
	.string "A bee-type\n"
	.string "Mechaniloid\n"
	.string "that stings.$"
.else
	.string "メルネット\n"
	.string "\n"
	.string "ハリを向けて、とんでくる\n"
	.string "ゴエイ用の\n"
	.string "ハチ型メカニロイド$"
.endif

Text_Disk_158:: @ 0x08375BBD
Str_311D:
.if ENGLISH
	.string "Shotcounter\n"
	.string "\n"
	.string "Can block\n"
	.string "frontal\n"
	.string "attacks.$"
.else
	.string "シャットカウンター\n"
	.string "\n"
	.string "前方からのコウゲキを\n"
	.string "ボウギョしている\n"
	.string "ひこう型メカニロイド$"
.endif

Text_Disk_159:: @ 0x08375BEA
Str_314A:
.if ENGLISH
	.string "Sharkseal X\n"
	.string "\n"
	.string "A shark-type\n"
	.string "Mechaniloid\n"
	.string "that bites.$"
.else
	.string "シャークシールX\n"
	.string "\n"
	.string "サメ型メカニロイドの\n"
	.string "カイリョウばんで\n"
	.string "エモノにかみついてくる$"
.endif

Text_Disk_160:: @ 0x08375C15
Str_3175:
.if ENGLISH
	.string "Shelluno\n"
	.string "\n"
	.string "Attacks from\n"
	.string "behind its\n"
	.string "target.$"
.else
	.string "シェルーノー\n"
	.string "\n"
	.string "ヒョウテキをサーチして\n"
	.string "おもに はいごから\n"
	.string "おそいかかってくる$"
.endif

Text_Disk_161:: @ 0x08375C3D
Str_319D:
.if ENGLISH
	.string "Icebon\n"
	.string "\n"
	.string "Produces ice\n"
	.string "underwater.$"
.else
	.string "アイスボン\n"
	.string "\n"
	.string "カイテイでコオリを\n"
	.string "セイゾウしている$"
.endif

Text_Disk_162:: @ 0x08375C57
Str_31B7:
.if ENGLISH
	.string "Shellcrawler\n"
	.string "\n"
	.string "Runs when it\n"
	.string "loses its\n"
	.string "shell.$"
.else
	.string "シェルクローラー\n"
	.string "\n"
	.string "ボウギョ用のカラを\n"
	.string "ハカイされると\n"
	.string "後方ににげていく$"
.endif

Text_Disk_163:: @ 0x08375C7F
Str_31DF:
.if ENGLISH
	.string "Cannonhopper\n"
	.string "\n"
	.string "Shoots from\n"
	.string "ceilings and\n"
	.string "floors.$"
.else
	.string "キャノンホッパー\n"
	.string "\n"
	.string "てんじょうやゆかに\n"
	.string "はりついて\n"
	.string "タマをばらまいてくる$"
.endif

Text_Disk_164:: @ 0x08375CA4
Str_3204:
.if ENGLISH
	.string "Weil\n"
	.string "\n"
	.string "Scientist \n"
	.string "who created\n"
	.string "Reploids.$"
.else
	.string "バイル\n"
	.string "\n"
	.string "ネオ・アルカディアで\n"
	.string "レプリロイドを\n"
	.string "作っていた科学者$"
.endif

Text_Disk_165:: @ 0x08375CC9
Str_3229:
.if ENGLISH
	.string "Ciel\n"
	.string "\n"
	.string "Researcher\n"
	.string "specializing\n"
	.string "in energy.$"
.else
	.string "シエル\n"
	.string "\n"
	.string "エネルギー開発を\n"
	.string "センモンとする\n"
	.string "科学者の少女$"
.endif

Text_Disk_166:: @ 0x08375CED
Str_324D:
.if ENGLISH
	.string "Cerveau\n"
	.string "\n"
	.string "Engineer who\n"
	.string "makes Zero's\n"
	.string "weapons.$"
.else
	.string "セルヴォ\n"
	.string "\n"
	.string "ゼロのために\n"
	.string "新しいブキを\n"
	.string "作ってくれるギジュツ者$"
.endif

Text_Disk_167:: @ 0x08375D10
Str_3270:
.if ENGLISH
	.string "Andrew\n"
	.string "\n"
	.string "Old Reploid\n"
	.string "who likes to\n"
	.string "talk a lot.$"
.else
	.string "アンドリュー\n"
	.string "\n"
	.string "むかし話を人に\n"
	.string "聞かせるのが大すきな\n"
	.string "ろうじん型のレプリロイド$"
.endif

Text_Disk_168:: @ 0x08375D3D
Str_329D:
.if ENGLISH
	.string "Alouette\n"
	.string "\n"
	.string "Treasures\n"
	.string "a doll Ciel\n"
	.string "gave her.$"
.else
	.string "アルエット\n"
	.string "\n"
	.string "シエルに作ってもらった\n"
	.string "人形をいつもダイジに\n"
	.string "かかえている$"
.endif

Text_Disk_169:: @ 0x08375D65
Str_32C5:
.if ENGLISH
	.string "Hibou\n"
	.string "\n"
	.string "This hungry\n"
	.string "Reploid eats\n"
	.string "E-Crystals.$"
.else
	.string "イブー\n"
	.string "\n"
	.string "Eクリスタルが\n"
	.string "何よりも大すきな\n"
	.string "くいしんぼうレプリロイド$"
.endif

Text_Disk_170:: @ 0x08375D8A
Str_32EA:
.if ENGLISH
	.string "Rocinolle\n"
	.string "\n"
	.string "Helps with\n"
	.string "wounded\n"
	.string "Reploids.$"
.else
	.string "ロシニョル\n"
	.string "\n"
	.string "メンテナンス・ルームで\n"
	.string "キズついたレジスタンスの\n"
	.string "手あてをしている$"
.endif

Text_Disk_171:: @ 0x08375DB4
Str_3314:
.if ENGLISH
	.string "Perroquiet\n"
	.string "\n"
	.string "A brilliant\n"
	.string "assistant\n"
	.string "to Ciel.$"
.else
	.string "ぺロケ\n"
	.string "\n"
	.string "ずのうメイセキで\n"
	.string "シエルの助手を\n"
	.string "つとめている$"
.endif

Text_Disk_172:: @ 0x08375DD3
Str_3333:
.if ENGLISH
	.string "Autruche\n"
	.string "\n"
	.string "A tall Rep-\n"
	.string "loid known\n"
	.string "for his dull\n"
	.string "speeches.$"
.else
	.string "オトリッシュ\n"
	.string "\n"
	.string "シンチョウが高く\n"
	.string "キョダツ感のある会話が\n"
	.string "とくちょう的な\n"
	.string "レプリロイド$"
.endif

Text_Disk_173:: @ 0x08375E04
Str_3364:
.if ENGLISH
	.string "Hirondelle\n"
	.string "\n"
	.string "Flies around\n"
	.string "and gathers\n"
	.string "information.$"
.else
	.string "イロンデル\n"
	.string "\n"
	.string "世界中をとびまわり、\n"
	.string "ありとあらゆる\n"
	.string "ジョウホウを集めている$"
.endif

Text_Disk_174:: @ 0x08375E2E
Str_338E:
.if ENGLISH
	.string "Doigt\n"
	.string "\n"
	.string "Cerveau's\n"
	.string "helper and\n"
	.string "weaponmaker.$"
.else
	.string "ドワ\n"
	.string "\n"
	.string "セルヴォの助手をつとめ\n"
	.string "レジスタンスのブキを\n"
	.string "作っている$"
.endif

Text_Disk_175:: @ 0x08375E52
Str_33B2:
.if ENGLISH
	.string "Menart\n"
	.string "\n"
	.string "A mischief-\n"
	.string "maker who\n"
	.string "plays hooky.$"
.else
	.string "メナート\n"
	.string "\n"
	.string "しごとをするのがきらいで\n"
	.string "いつもサボってばかりいる\n"
	.string "いたずらっこ$"
.endif

Text_Disk_176:: @ 0x08375E79
Str_33D9:
.if ENGLISH
	.string "Pic\n"
	.string "\n"
	.string "A cynical\n"
	.string "Reploid who\n"
	.string "makes snide\n"
	.string "comments.$"
.else
	.string "ピック\n"
	.string "\n"
	.string "口を開けば\n"
	.string "イヤミなことばかり言う\n"
	.string "少しひねくれた\n"
	.string "レプリロイド$"
.endif

Text_Disk_177:: @ 0x08375EA3
Str_3403:
.if ENGLISH
	.string "Harpuia\n"
	.string "\n"
	.string "The shrewd\n"
	.string "Green Lord\n"
	.string "leads the\n"
	.string "Rekku Army.$"
.else
	.string "ハルピュイア\n"
	.string "\n"
	.string "賢将のイミョウをもつ\n"
	.string "緑の四天王。\n"
	.string "レックウ軍団を\n"
	.string "ひきいる$"
.endif

Text_Disk_178:: @ 0x08375ED2
Str_3432:
.if ENGLISH
	.string "Fefnir\n"
	.string "\n"
	.string "The fierce\n"
	.string "Red Lord\n"
	.string "leads the\n"
	.string "Jin'en Army.$"
.else
	.string "ファーブニル\n"
	.string "\n"
	.string "闘将のイミョウをもつ\n"
	.string "赤き四天王。\n"
	.string "ジンエン軍団を\n"
	.string "ひきいる$"
.endif

Text_Disk_179:: @ 0x08375F01
Str_3461:
.if ENGLISH
	.string "Leviathan\n"
	.string "\n"
	.string "The sly\n"
	.string "Blue Lord\n"
	.string "leads the\n"
	.string "Meikai Army.$"
.else
	.string "レヴィアタン\n"
	.string "\n"
	.string "妖将のイミョウをもつ\n"
	.string "青き四天王。\n"
	.string "メイカイ軍団を\n"
	.string "ひきいる$"
.endif

Text_Disk_180:: @ 0x08375F30
Str_3490:
.if ENGLISH
	.string "Phantom\n"
	.string "\n"
	.string "The evil\n"
	.string "Dark Lord\n"
	.string "Leads the\n"
	.string "Zan'ei Army.$"
.else
	.string "ファントム\n"
	.string "\n"
	.string "隠将のイミョウをもつ\n"
	.string "ヤミの四天王。\n"
	.string "ザンエイ軍団を\n"
	.string "ひきいる$"
.endif
