/*
  GENERATED by tools/gen_ap_orbit.py -- do not edit by hand.

  The Archipelago logo's six colours, its dot, and the orbit, for the marker on an
  unchecked 1-UP. Colours are sampled from ZeroArchipelago/data/icon.png; the shape is
  DOT_ART in the generator; the geometry comes from the #defines in ap_orbit.h.

  Archipelago logo (c) 2022 Krista Corkos and Christopher Wilson, CC BY-NC 4.0.
*/
#include "ap_orbit.h"
#include "global.h"

#if AP

const u16 gApOrbitPalette[16] = {
    0x0000, 0x41D9, 0x292F, 0x4B9D,
    0x2E32, 0x3B0E, 0x25E9, 0x5DEE,
    0x3929, 0x6259, 0x3D6F, 0x3E9B,
    0x2590, 0x7FFF, 0x0000, 0x0000,
};

const u32 gApOrbitTiles[AP_ORBIT_TILE_COUNT][8] = {
    {0x00000000, 0x00022000, 0x00211200, 0x02111120, 0x02111120, 0x00211200, 0x00022000, 0x00000000,},
    {0x00000000, 0x00044000, 0x00433400, 0x04333340, 0x04333340, 0x00433400, 0x00044000, 0x00000000,},
    {0x00000000, 0x00066000, 0x00655600, 0x06555560, 0x06555560, 0x00655600, 0x00066000, 0x00000000,},
    {0x00000000, 0x00088000, 0x00877800, 0x08777780, 0x08777780, 0x00877800, 0x00088000, 0x00000000,},
    {0x00000000, 0x000AA000, 0x00A99A00, 0x0A9999A0, 0x0A9999A0, 0x00A99A00, 0x000AA000, 0x00000000,},
    {0x00000000, 0x000CC000, 0x00CBBC00, 0x0CBBBBC0, 0x0CBBBBC0, 0x00CBBC00, 0x000CC000, 0x00000000,},
    {0x00000000, 0x00022000, 0x00211200, 0x02111120, 0x02111120, 0x00211200, 0x00022000, 0x00000000,},
    {0x00000000, 0x00044000, 0x00433400, 0x04333340, 0x04333340, 0x00433400, 0x00044000, 0x00000000,},
    {0x00000000, 0x00066000, 0x00655600, 0x06555560, 0x06555560, 0x00655600, 0x00066000, 0x00000000,},
    {0x00000000, 0x00088000, 0x00877800, 0x08777780, 0x08777780, 0x00877800, 0x00088000, 0x00000000,},
    {0x00000000, 0x000AA000, 0x00A99A00, 0x0A9999A0, 0x0A9999A0, 0x00A99A00, 0x000AA000, 0x00000000,},
    {0x00000000, 0x000CC000, 0x00CBBC00, 0x0CBBBBC0, 0x0CBBBBC0, 0x00CBBC00, 0x000CC000, 0x00000000,},
};

const struct ApOrbitSprite gApOrbitSprite = {
    hdr : {
      {ofs : 32, subspriteCount : 6, texture : 0},
      {ofs : 56, subspriteCount : 6, texture : 0},
      {ofs : 80, subspriteCount : 6, texture : 0},
      {ofs : 104, subspriteCount : 6, texture : 0},
      {ofs : 128, subspriteCount : 6, texture : 0},
      {ofs : 152, subspriteCount : 6, texture : 0},
      {ofs : 176, subspriteCount : 6, texture : 0},
      {ofs : 200, subspriteCount : 6, texture : 0},
    },
    dot : {
      {{tileNum : 0, x : 9, y : -9}, {tileNum : 1, x : 3, y : 2}, {tileNum : 2, x : -10, y : 2}, {tileNum : 3, x : -17, y : -9}, {tileNum : 4, x : -11, y : -20}, {tileNum : 5, x : 3, y : -20}},
      {{tileNum : 0, x : 9, y : -7}, {tileNum : 1, x : 1, y : 3}, {tileNum : 2, x : -12, y : 1}, {tileNum : 3, x : -17, y : -11}, {tileNum : 4, x : -9, y : -21}, {tileNum : 5, x : 4, y : -19}},
      {{tileNum : 0, x : 9, y : -6}, {tileNum : 1, x : -1, y : 4}, {tileNum : 2, x : -13, y : 0}, {tileNum : 3, x : -17, y : -12}, {tileNum : 4, x : -7, y : -22}, {tileNum : 5, x : 5, y : -18}},
      {{tileNum : 0, x : 8, y : -4}, {tileNum : 1, x : -2, y : 4}, {tileNum : 2, x : -14, y : -1}, {tileNum : 3, x : -16, y : -14}, {tileNum : 4, x : -6, y : -22}, {tileNum : 5, x : 6, y : -17}},
      {{tileNum : 0, x : 7, y : -3}, {tileNum : 1, x : -4, y : 4}, {tileNum : 2, x : -15, y : -3}, {tileNum : 3, x : -15, y : -16}, {tileNum : 4, x : -4, y : -22}, {tileNum : 5, x : 7, y : -16}},
      {{tileNum : 0, x : 6, y : -1}, {tileNum : 1, x : -6, y : 4}, {tileNum : 2, x : -16, y : -4}, {tileNum : 3, x : -14, y : -17}, {tileNum : 4, x : -2, y : -22}, {tileNum : 5, x : 8, y : -14}},
      {{tileNum : 0, x : 5, y : 0}, {tileNum : 1, x : -7, y : 4}, {tileNum : 2, x : -17, y : -6}, {tileNum : 3, x : -13, y : -18}, {tileNum : 4, x : -1, y : -22}, {tileNum : 5, x : 9, y : -12}},
      {{tileNum : 0, x : 4, y : 1}, {tileNum : 1, x : -9, y : 3}, {tileNum : 2, x : -17, y : -7}, {tileNum : 3, x : -12, y : -19}, {tileNum : 4, x : 1, y : -21}, {tileNum : 5, x : 9, y : -11}},
    },
};

#endif /* AP */
